In [1]:
%load_ext autoreload
%autoreload 2
%load_ext watermark
%watermark -v -n -m -p numpy,scipy,sklearn,pandas

Sat Dec 29 2018 

CPython 3.6.6
IPython 6.5.0

numpy 1.15.1
scipy 1.1.0
sklearn 0.19.1
pandas 0.23.4

compiler   : GCC 4.8.2 20140120 (Red Hat 4.8.2-15)
system     : Linux
release    : 4.9.0-7-amd64
machine    : x86_64
processor  : 
CPU cores  : 12
interpreter: 64bit


In [2]:
%matplotlib inline
import sys
import pandas as pd
import numpy as np
import seaborn as sns
import os
import nolds
import data
import mne

PROJ_ROOT = os.path.abspath(os.path.join(os.pardir))
DATA_ROOT = os.path.abspath(os.path.join(PROJ_ROOT, 'data'))
PROCESSED_ROOT = os.path.abspath(os.path.join(DATA_ROOT, 'processed'))
RAW_ROOT = os.path.abspath(os.path.join(DATA_ROOT, 'raw'))
LABELED_ROOT = os.path.abspath(os.path.join(DATA_ROOT, 'labeled'))
DURATIONS_ROOT = os.path.abspath(os.path.join(DATA_ROOT, 'durations'))
sys.path.append(os.path.join(PROJ_ROOT, 'src'))
CHANNEL_NAMES = ['FP1', 'FP2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2',
                 'F7', 'F8', 'T3', 'T4', 'T5', 'T6', 'Fz', 'Cz', 'Pz']
META_COLUMN_NAMES = ['freq', 'RESP_4W', 'RESP_FIN', 'REMISE_FIN', 'AGE', 'SEX', 'M_1',
       'M_4', 'M_F', 'délka léčby', 'lék 1', 'lék 2', 'lék 3', 'lék 4']
META_FILE_NAME = 'DEP-POOL_Final_144.xlsx'
meta_df = pd.read_excel(os.path.join(RAW_ROOT, META_FILE_NAME), index_col='ID', names=META_COLUMN_NAMES)

raw_fif = mne.io.read_raw_fif(os.path.join(PROCESSED_ROOT, '1a.fif'))
t = pd.DataFrame(raw_fif.get_data())
data = pd.DataFrame(np.transpose(t.values), columns=CHANNEL_NAMES)
data = np.transpose(data.values)
metapkl = pd.read_pickle(os.path.join(LABELED_ROOT, 'processed', 'meta', 'meta.pkl'))
metapkl

Opening raw data file /home/kovar/thesis_project/data/processed/1a.fif...
This filename (/home/kovar/thesis_project/data/processed/1a.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, raw.fif.gz, raw_sss.fif.gz or raw_tsss.fif.gz
Isotrak not found
    Range : 0 ... 19104 =      0.000 ...    76.416 secs
Ready.


<ipython-input-2-2bb109ef8967>:25: RuntimeWarning: This filename (/home/kovar/thesis_project/data/processed/1a.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, raw.fif.gz, raw_sss.fif.gz or raw_tsss.fif.gz
  raw_fif = mne.io.read_raw_fif(os.path.join(PROCESSED_ROOT, '1a.fif'))


resp b/a sex  age    sc  sc_bef  sc_aft  dep  dep_bef  dep_aft  \
patient trial                                                                  
1       a        1   0   0   49  26.0      26      13    0        0        0   
        b        1   1   0   49  13.0      26      13   -1        0        0   
2       a        0   0   0   36  31.0      31      30    1        1        1   
        b        0   1   0   36  30.0      31      30    1        1        1   
3       a        1   0   0   48  25.0      25       7    0       -1       -1   
        b        1   1   0   48   7.0      25       7   -1       -1       -1   
4       a        0   0   0   55  26.0      26      25    0        0        1   
        b        0   1   0   55  25.0      26      25    0        0        1   
5       a        0   0   0   35  26.0      26      37    0        0        1   
        b        0   1   0   35  37.0      26      37    1        0        1   
6       a        0   0   0   37  31.0      31      17    1        1        0   
        b        0   1   0   37  17.0      31      17   -1        1        0   
7       a        0   0   0   63  30.0      30      25    1        1        1   
        b        0   1   0   63  25.0      30      25    0        1        1   
8       a        1   0   1   50  24.0      24      11    0       -1       -1   
        b        1   1   1   50  11.0      24      11   -1       -1       -1   
9       a        0   0   1   59  34.0      34      27    1        1        1   
        b        0   1   1   59  27.0      34      27    1        1        1   
10      a        1   0   0   49  36.0      36      17    1        1        0   
        b        1   1   0   49  17.0      36      17   -1        1        0   
11      a        0   0   1   53  27.0      27      26    1        0        1   
        b        0   1   1   53  26.0      27      26    0        0        1   
12      a        1   0   1   59  30.0      30      12    1        1       -1   
        b        1   1   1   59  12.0      30      12   -1        1       -1   
13      a        1   0   0   57  26.0      26       7    0        0       -1   
        b        1   1   0   57   7.0      26       7   -1        0       -1   
14      a        0   0   0   30  28.0      28      17    1        0        0   
        b        0   1   0   30  17.0      28      17   -1        0        0   
15      a        1   0   0   35  25.0      25       3    0       -1       -1   
        b        1   1   0   35   3.0      25       3   -1       -1       -1   
...            ...  ..  ..  ...   ...     ...     ...  ...      ...      ...   
119     a        1   0   1   61  23.0      23       4    0       -1       -1   
        b        1   1   1   61   4.0      23       4   -1       -1       -1   
120     a        0   0   0   41  28.0      28      19    1        0        0   
        b        0   1   0   41  19.0      28      19   -1        0        0   
121     a        0   0   0   34  24.0      24      26    0       -1        1   
        b        0   1   0   34  26.0      24      26    0       -1        1   
122     a        0   0   1   55  35.0      35      19    1        1        0   
        b        0   1   1   55  19.0      35      19   -1        1        0   
123     a        0   0   1   54  24.0      24      25    0       -1        1   
        b        0   1   1   54  25.0      24      25    0       -1        1   
124     a        0   0   0   52  30.0      30      23    1        1        1   
        b        0   1   0   52  23.0      30      23    0        1        1   
125     a        1   0   0   56  26.0      26      11    0        0       -1   
        b        1   1   0   56  11.0      26      11   -1        0       -1   
126     a        0   0   0   40  25.0      25      17    0       -1        0   
        b        0   1   0   40  17.0      25      17   -1       -1        0   
127     a        0   0   0   35  25.0      25      21    0       -1        1   
        b     

In [106]:
def f(row, col):
    if row[col] <= 19:
        return -1
    if row[col] <= 34:
        return 0
    else:
        return 1
def ff(row, col, n=5):
    for i in range(n):
        if row[col] <= metapkl.quantile((i+1)/n)[col]:
            return i
    
metapkl['dep'] = metapkl.apply(lambda row: ff(row, 'sc'), axis=1)
metapkl['dep_bef'] = metapkl.apply(lambda row: ff(row, 'sc_bef'), axis=1)
metapkl['dep_aft'] = metapkl.apply(lambda row: ff(row, 'sc_aft'), axis=1)
metapkl = metapkl.astype({'dep': 'category', 'dep_bef': 'category', 'dep_aft': 'category'})                                           
print(metapkl['dep'].value_counts())
print(metapkl['dep_bef'].value_counts())
print(metapkl['dep_aft'].value_counts())

3    58
2    55
0    55
1    54
4    44
Name: dep, dtype: int64
0    100
3     56
2     44
4     40
1     26
Name: dep_bef, dtype: int64
0    68
3    58
2    50
4    48
1    42
Name: dep_aft, dtype: int64


In [9]:
def prepare_dfs(col='lyap', kind='processed'):
    df = pd.read_pickle(os.path.join(LABELED_ROOT, kind, col, f'training_{col}.pkl')).dropna()
    df_bef = pd.read_pickle(os.path.join(LABELED_ROOT, kind, col, f'{col}_bef.pkl')).dropna()
    df_aft = pd.read_pickle(os.path.join(LABELED_ROOT, kind, col, f'{col}_aft.pkl')).dropna()
    return df, df_bef, df_aft
    
def prepare_resp_non(col='lyap'):
    df, df_bef, df_aft = prepare_dfs(col)
    return df[df['change'] >= df.quantile(0.66)['change']], df[df['change'] <= df.quantile(0.33)['change']]

col = 'sampen'
df, df_bef, df_aft = prepare_dfs(col)
# df_resp, df_non = prepare_resp_non(col)
dfs = pd.read_pickle(os.path.join(LABELED_ROOT, 'sampen_2_20std_v2.pkl')).dropna()
dfs.loc[:, ('FP1', 'sampen')], df.loc[:, 'FP1']

(patient  trial
 1        a         0.72981
          b        0.923777
 2        b        0.695432
 3        a        0.615735
          b         0.63424
 4        a        0.673677
          b        0.671692
 5        a        0.706208
          b        0.704847
 6        b        0.748886
 7        a        0.711422
          b        0.683571
 8        b        0.616167
 9        a        0.718685
          b        0.668687
 10       a         1.01236
          b        0.890757
 11       a        0.810429
          b        0.876173
 12       a        0.583416
          b         1.11319
 13       b         1.01368
 14       a        0.778871
          b        0.683626
 15       a        0.763933
          b        0.682654
 16       a        0.687646
          b         0.70633
 17       a        0.923322
          b        0.885992
                     ...   
 117      a        0.798574
          b        0.851442
 118      a        0.998488
 119      a        0.716905
    

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import (SelectFromModel, RFE, RFECV, SelectKBest, mutual_info_classif)
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm, grid_search, datasets
from genetic_selection import GeneticSelectionCV
from functools import wraps
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB

def print_params(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        print(f'{args} {kwargs}')
        res = f(*args, **kwargs)
        return res
    return wrapper

@print_params
def predict(lab, ba, cols, selector):
    df, df_bef, df_aft = prepare_dfs('all')
    df = df.loc[(slice(None), slice(ba)), (CHANNEL_NAMES, (cols))]
    X = df
    X = X.drop(metapkl.columns, axis=1, errors='ignore')
    y = X.join(metapkl)[lab]
    
    X_train, X_test, y_train, y_test = \
        train_test_split(
            X, y, test_size=0.3, random_state=213)
    
    # unique, counts = np.unique(y_train, return_counts=True) 
    # print(counts[0] / (counts[0] + counts[1]))
    unique, counts = np.unique(y_train, return_counts=True)
    print(dict(zip(unique, counts)))
    unique, counts = np.unique(y_test, return_counts=True)
    print(dict(zip(unique, counts)))

    y_train = y_train.astype('int')

    selector.fit(X_train, y_train)
    y_pred = selector.predict(X_test)
    y_pred = y_pred.astype('int')
    y_test = y_test.astype('int')

    print("Accuracy score: %.2f" % metrics.accuracy_score(y_test, y_pred))
    print('Confusion matrix:\n ', metrics.confusion_matrix(y_test, y_pred))
    print('Precision score: ', metrics.precision_score(y_test, y_pred, average='weighted'))
    print('Recall score: ', metrics.recall_score(y_test, y_pred, average='weighted'))
    print('f1 score: ', metrics.f1_score(y_test, y_pred, average='weighted'))
    # print('Coefficients: \n', np.array(X.stack().columns)[selector.support_])

In [15]:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

def scorer(estimator, X, y):
    y_pred = estimator.predict(X)
    return (metrics.f1_score(y, y_pred, average='weighted') 
            + metrics.precision_score(y, y_pred, average='weighted') 
            + metrics.recall_score(y, y_pred, average='weighted') 
            + metrics.accuracy_score(y, y_pred))

estimator_svc = grid_search.GridSearchCV(svm.SVC(class_weight='balanced'), {
    'C': [0.02, 0.5, 1.0, 1.5, 2],
    # 'kernel': ('linear', 'poly', 'rbf', 'sigmoid'),
    'shrinking': (True, False),
    # 'decision_function_shape' : ('ovo', 'ovr'),
}, iid=False, scoring=scorer)

estimator_lg = grid_search.GridSearchCV(LogisticRegression(class_weight='balanced'), {
    'C': [0.5, 1.0, 1.5, 2, 2.5, 3, 3.5],
    'penalty': ['l2', 'l1'],
}, iid=False, scoring=scorer)

estimators = {
    svm.SVC(class_weight='balanced'): {
        'C': [0.02, 0.5, 1.0, 1.5, 2],
        # 'kernel': ('linear', 'poly', 'rbf', 'sigmoid'),
        'shrinking': (True, False),
        # 'decision_function_shape' : ('ovo', 'ovr'),
    },
    LogisticRegression(class_weight='balanced'): {
        'C': [0.5, 1.0, 1.5, 2, 2.5, 3, 3.5],
        'penalty': ['l2', 'l1'],
    }
}

cols = ('lyap', 'corr', 'dfa', 'sampen')

for estimator, params in estimators.items():
    for cols in (('lyap', 'corr', 'dfa', 'sampen'), ('lyap'), ('corr'), ('dfa'), ('sampen')):
        for selector in (RFECV(estimator), GeneticSelectionCV(estimator,
                                          cv=3,
                                          verbose=0,
                                          scoring=scorer,
                                          n_population=50,
                                          crossover_proba=0.8,
                                          mutation_proba=0.2,
                                          n_generations=50,
                                          crossover_independent_proba=0.5,
                                          mutation_independent_proba=0.05,
                                          tournament_size=3,
                                          caching=True,
                                          n_jobs=-1)):
            selector = grid_search.GridSearchCV(selector, params, iid=False, scoring=scorer)
            # predict('dep', None, cols, selector)
            predict('dep_bef', 'a', cols, selector.estimator.estimator)
            # predict('dep_aft', 'b', cols, selector)
            # predict('resp', 'b', cols, selector)

('dep_bef', 'a', ('lyap', 'corr', 'dfa', 'sampen'), SVC(C=1.0, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)) {}
{-1: 31, 0: 28, 1: 25}
{-1: 14, 0: 14, 1: 8}
Accuracy score: 0.33
Confusion matrix:
  [[ 1 10  3]
 [ 4  8  2]
 [ 1  4  3]]
Precision score:  0.2895622895622896
Recall score:  0.3333333333333333
f1 score:  0.29506172839506173
('dep_bef', 'a', ('lyap', 'corr', 'dfa', 'sampen'), SVC(C=1.0, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)) {}
{-1: 31, 0: 28, 1: 25}
{-1: 14, 0: 14, 1: 8}
Accuracy score: 0.33
Confusion matrix:
  [[ 1 10  3]
 [ 4  8  2]
 [ 1  4  3]]
Precision score:  0.2895622895622896
Recall score:  0.3333333333333333
f1 scor

{-1: 31, 0: 28, 1: 25}
{-1: 14, 0: 14, 1: 8}
Accuracy score: 0.56
Confusion matrix:
  [[10  4  0]
 [ 5  8  1]
 [ 3  3  2]]
Precision score:  0.571604938271605
Recall score:  0.5555555555555556
f1 score:  0.5384230233368165
('dep_bef', 'a', 'sampen', LogisticRegression(C=1.0, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)) {}
{-1: 31, 0: 28, 1: 25}
{-1: 14, 0: 14, 1: 8}
Accuracy score: 0.36
Confusion matrix:
  [[7 7 0]
 [8 4 2]
 [5 1 2]]
Precision score:  0.3768518518518518
Recall score:  0.3611111111111111
f1 score:  0.3538629126864421
('dep_bef', 'a', 'sampen', LogisticRegression(C=1.0, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol

In [ ]:
df = pd.rea