In [1]:
%load_ext autoreload
%autoreload 2
%load_ext watermark
%watermark -v -n -m -p numpy,scipy,sklearn,pandas

Mon Jan 14 2019 

CPython 3.6.6
IPython 6.5.0

numpy 1.15.1
scipy 1.1.0
sklearn 0.19.1
pandas 0.23.4

compiler   : GCC 4.8.2 20140120 (Red Hat 4.8.2-15)
system     : Linux
release    : 4.9.0-7-amd64
machine    : x86_64
processor  : 
CPU cores  : 12
interpreter: 64bit


In [2]:
%matplotlib inline
import sys
import pandas as pd
import numpy as np
import seaborn as sns
import os
import nolds
import data
import mne
from random import randint

PROJ_ROOT = os.path.abspath(os.path.join(os.pardir))
DATA_ROOT = os.path.abspath(os.path.join(PROJ_ROOT, 'data'))
PROCESSED_ROOT = os.path.abspath(os.path.join(DATA_ROOT, 'processed'))
RAW_ROOT = os.path.abspath(os.path.join(DATA_ROOT, 'raw'))
LABELED_ROOT = os.path.abspath(os.path.join(DATA_ROOT, 'labeled'))
DURATIONS_ROOT = os.path.abspath(os.path.join(DATA_ROOT, 'durations'))
sys.path.append(os.path.join(PROJ_ROOT, 'src'))
CHANNEL_NAMES = ['FP1', 'FP2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2',
                 'F7', 'F8', 'T3', 'T4', 'T5', 'T6', 'Fz', 'Cz', 'Pz']
META_COLUMN_NAMES = ['freq', 'RESP_4W', 'RESP_FIN', 'REMISE_FIN', 'AGE', 'SEX', 'M_1',
       'M_4', 'M_F', 'délka léčby', 'lék 1', 'lék 2', 'lék 3', 'lék 4']
META_FILE_NAME = 'DEP-POOL_Final_144.xlsx'
meta_df = pd.read_excel(os.path.join(RAW_ROOT, META_FILE_NAME), index_col='ID', names=META_COLUMN_NAMES)

raw_fif = mne.io.read_raw_fif(os.path.join(PROCESSED_ROOT, '1a.fif'))
t = pd.DataFrame(raw_fif.get_data())
data = pd.DataFrame(np.transpose(t.values), columns=CHANNEL_NAMES)
data = np.transpose(data.values)
metapkl = pd.read_pickle(os.path.join(LABELED_ROOT, 'processed', 'meta', 'meta.pkl'))
metapkl

Opening raw data file /home/kovar/thesis_project/data/processed/1a.fif...
This filename (/home/kovar/thesis_project/data/processed/1a.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, raw.fif.gz, raw_sss.fif.gz or raw_tsss.fif.gz
Isotrak not found
    Range : 0 ... 19104 =      0.000 ...    76.416 secs
Ready.


<ipython-input-2-33b7c9fcedde>:26: RuntimeWarning: This filename (/home/kovar/thesis_project/data/processed/1a.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, raw.fif.gz, raw_sss.fif.gz or raw_tsss.fif.gz
  raw_fif = mne.io.read_raw_fif(os.path.join(PROCESSED_ROOT, '1a.fif'))


resp b/a sex  age  sfreq    sc  sc_bef  sc_aft dep dep_bef  \
patient trial                                                              
1       a        1   0   0   49    250  26.0      26      13   0       0   
        b        1   1   0   49    250  13.0      26      13  -1       0   
2       a       -1   0   0   36    250  31.0      31      30   1       1   
        b       -1   1   0   36    250  30.0      31      30   1       1   
3       a        1   0   0   48    250  25.0      25       7   0       0   
        b        1   1   0   48    250   7.0      25       7  -1       0   
4       a       -1   0   0   55    250  26.0      26      25   0       0   
        b       -1   1   0   55    250  25.0      26      25   0       0   
5       a       -1   0   0   35    250  26.0      26      37   0       0   
        b       -1   1   0   35    250  37.0      26      37   1       0   
6       a        0   0   0   37    250  31.0      31      17   1       1   
        b        0   1   0   37    250  17.0      31      17   0       1   
7       a       -1   0   0   63    250  30.0      30      25   1       1   
        b       -1   1   0   63    250  25.0      30      25   0       1   
8       a        1   0   1   50    250  24.0      24      11   0       0   
        b        1   1   1   50    250  11.0      24      11  -1       0   
9       a       -1   0   1   59    250  34.0      34      27   1       1   
        b       -1   1   1   59    250  27.0      34      27   0       1   
10      a        1   0   0   49    250  36.0      36      17   1       1   
        b        1   1   0   49    250  17.0      36      17   0       1   
11      a       -1   0   1   53   1000  27.0      27      26   0       0   
        b       -1   1   1   53   1000  26.0      27      26   0       0   
12      a        1   0   1   59   1000  30.0      30      12   1       1   
        b        1   1   1   59   1000  12.0      30      12  -1       1   
13      a        1   0   0   57    250  26.0      26       7   0       0   
        b        1   1   0   57    250   7.0      26       7  -1       0   
14      a        0   0   0   30    250  28.0      28      17   0       0   
        b        0   1   0   30    250  17.0      28      17   0       0   
15      a        1   0   0   35   1000  25.0      25       3   0       0   
        b        1   1   0   35   1000   3.0      25       3  -1       0   
...            ...  ..  ..  ...    ...   ...     ...     ...  ..     ...   
119     a        1   0   1   61    250  23.0      23       4   0       0   
        b        1   1   1   61    250   4.0      23       4  -1       0   
120     a       -1   0   0   41   1000  28.0      28      19   0       0   
        b       -1   1   0   41   1000  19.0      28      19   0       0   
121     a       -1   0   0   34    250  24.0      24      26   0       0   
        b       -1   1   0   34    250  26.0      24      26   0       0   
122     a        0   0   1   55    250  35.0      35      19   1       1   
        b        0   1   1   55    250  19.0      35      19   0       1   
123     a       -1   0   1   54    250  24.0      24      25   0       0   
        b       -1   1   1   54    250  25.0      24      25   0       0   
124     a       -1   0   0   52    250  30.0      30      23   1       1   
        b       -1   1   0   52    250  23.0      30      23   0       1   
125     a        1   0   0   56    250  26.0      26      11   0       0   
        b        1   1   0   56    250  11.0      26      11  -1       0   
126     a       -1   0   0   40    250  25.0      25      17   0       0   
        b       -1   1   0   40    250  17.0      25      17   0       0   
127     a       -1   0   0   35    250  25.0      25      21   0       0   
        b       -1   1   0   35    250  21.0      25      21   0       0   
128     a        1   0   0   51    250  21.0      21       9   0       0   
        b        1   1   0   51    250   9.0      21       9  

In [3]:
def f(row, col):
    if row[col] <= 16:
        return -1
    if row[col] <= 28:
        return 0
    else:
        return 1
def ff(row, col, n=5):
    for i in range(n):
        if row[col] <= metapkl.quantile((i+1)/n)[col]:
            return i
    
metapkl['dep'] = metapkl.apply(lambda row: f(row, 'sc'), axis=1)
metapkl['dep_bef'] = metapkl.apply(lambda row: f(row, 'sc_bef'), axis=1)
metapkl['dep_aft'] = metapkl.apply(lambda row: f(row, 'sc_aft'), axis=1)
metapkl = metapkl.astype({'dep': 'category', 'dep_bef': 'category', 'dep_aft': 'category'})                                           
print(metapkl['dep'].value_counts())
print(metapkl['dep_bef'].value_counts())
print(metapkl['dep_aft'].value_counts())
def f(row, col):
    if row[col] <= metapkl.quantile(0.33)['change']:
        return -1
    if row[col] <= metapkl.quantile(0.66)['change']:
        return 0
    else:
        return 1
    
metapkl['resp'] = metapkl.apply(lambda row: f(row, 'change'), axis=1)
metapkl = metapkl.astype({'resp': 'category'})                                           
print(metapkl['resp'].value_counts())

 0    148
-1     62
 1     56
Name: dep, dtype: int64
0    170
1     96
Name: dep_bef, dtype: int64
 0    126
-1    124
 1     16
Name: dep_aft, dtype: int64
 1    90
 0    88
-1    88
Name: resp, dtype: int64


In [4]:
def prepare_dfs(col='lyap', kind='processed'): 
    bands = {'delta', 'theta', 'alpha', 'beta', 'gamma'}
    band = None
    if col in bands:
        band = col
        col = 'ampl'
    df = pd.read_pickle(os.path.join(LABELED_ROOT, kind, col, f'training_{col}.pkl')) 
    df_bef = pd.read_pickle(os.path.join(LABELED_ROOT, kind, col, f'{col}_bef.pkl'))
    df_aft = pd.read_pickle(os.path.join(LABELED_ROOT, kind, col, f'{col}_aft.pkl'))
    if band is not None:
        df = df.loc[:, (slice(None), band)]
        df_bef = df_bef.loc[:, (slice(None), band)]
        df_aft = df_aft.loc[:, (slice(None), band)]
    return df, df_bef, df_aft
    
def prepare_resp_non(col='lyap'):
    df, df_bef, df_aft = prepare_dfs(col)
    df = df.drop(metapkl.columns, axis=1, errors='ignore')
    df.columns = df.columns.droplevel(1)
    df = df.join(metapkl)
    return df[df['dep'] == 1], df[df['dep'] == -1]

def prepare_dep_non(col='lyap'):
    df, df_bef, df_aft = prepare_dfs(col)
    df = df.drop(metapkl.columns, axis=1, errors='ignore')
    df.columns = df.columns.droplevel(1)
    df = df.join(metapkl)
    return df[df['dep'] == 1], df[df['dep'] == -1]

col = 'lyap'
df, df_bef, df_aft = prepare_dfs(col)
df_dep, df_nond =  prepare_dep_non(col)
df_resp, df_non = prepare_resp_non(col)
df

channel              FP1        FP2         F3         F4         C3  \
measure             lyap       lyap       lyap       lyap       lyap   
patient trial                                                          
1       a      10.029887  11.703816   9.214353   9.940690   9.454637   
        b       8.682294  10.005590  10.394913   8.533577   8.583511   
3       a      11.491857  11.446344  11.668608  11.491566  11.875358   
        b      11.063547  11.302472  11.271126  11.381274  10.575230   
4       a      11.049518  11.246144  10.800703  11.212004  10.770177   
        b      10.757364  11.094023  10.519614  10.856012  10.200112   
5       a      10.608832  10.429371   9.958579   9.779142   9.767949   
        b      10.222496  10.364009   9.902109   9.551293   9.522670   
7       a      10.569585  10.164602  10.603027  10.453541  10.934872   
        b      11.379479  11.042357  11.379592  11.002860  11.359843   
9       a      10.462948  10.407645  10.633778  10.445797  10.052567   
        b      10.800397  10.845411  10.624771  10.652032  10.339373   
10      a       8.464631   8.587235   8.304111   8.648945   8.438431   
        b       9.381783   9.358838   8.992300   9.070511   8.996572   
11      a       9.938870  10.700517   9.982946  10.238261  10.231401   
        b       9.597677   9.999793   8.112257   9.467099   7.250574   
12      a      10.559718   8.606021   8.862489   9.546337   9.779549   
        b       7.814297   8.188641   8.665411  10.588183  10.072393   
14      a       9.574759  10.230881   9.277384  10.030223   9.738008   
        b      10.455687   9.639854   9.724015   9.776478   9.459171   
15      a      10.113879   8.980166   9.024871   8.755189   8.550213   
        b      10.213675   8.199658   9.628821   8.228489   8.485771   
16      a       9.846539  10.168192  10.563270  10.465832  11.160680   
        b      10.231329  10.399685  10.562711  10.484028  10.836115   
17      a       8.544387   8.928190   8.487922   8.528657   8.208459   
        b       8.921241   8.695206   8.810930   9.045643  10.285132   
18      a       7.132538   7.103452   6.896109   7.650140   7.509271   
        b       6.726034   6.874946   7.176765   6.694113   7.099843   
19      a      10.419511  10.409738  10.753326  11.127189  11.109778   
        b      11.177304  11.017616  10.894344  10.525374  11.226285   
...                  ...        ...        ...        ...        ...   
115     a      10.177573  10.463498  10.373667  10.284192  10.520390   
        b      10.210878  10.337421  10.198964  10.465757  10.249467   
116     a       7.578186   6.806090   8.358481   8.554304   7.985535   
        b       8.592089   7.213457   8.524504   8.473015   7.765644   
117     a       9.409438   8.855185  10.345424   9.985462   9.148281   
        b       9.151351   8.514548  10.339608  10.181550  10.225834   
119     a      10.677304  10.673568  10.311946  10.528846  10.119253   
        b      10.101010  10.864712  10.305223   9.961157  10.192525   
121     a      10.629734  10.485277  10.785476  10.822141   9.594741   
        b       7.236057   9.101107   9.673147  10.426984  10.405070   
122     a       9.499462  11.296125   9.031831  11.727797  11.066806   
        b       9.605622  11.644169  10.744784  11.550937  11.453431   
123     a      10.584845  11.341327  11.253140  11.454313  10.748692   
        b       9.275467   9.925772   8.176311   7.202035   8.525424   
124     a       9.711738  10.061197   9.882326   9.801841  10.521407   
        b       9.185143   9.598477   9.021667   9.168765   9.654120   
126     a       8.926742  10.608816   9.474970   9.487009   8.818930   
        b      10.156676  11.037440  10.473964  10.823342  10.330702   
127     a      10.117673  10.394623   9.646045  10.417927  10.236393   
        b       8.861269   9.498562   9.144958   9.890549   9.491379   
129     a      10.110227  10.423039  10.306522  10.400453  10.823231   
        b       9.295682   9.270439   8.

In [5]:
#### from sklearn.model_selection import train_test_split
from sklearn.feature_selection import (SelectFromModel, RFE, RFECV, SelectKBest, mutual_info_classif, chi2)
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_validate
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm, grid_search, datasets
from genetic_selection import GeneticSelectionCV
from functools import wraps
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB

def print_params(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        print(f'{args} {kwargs}')
        res = f(*args, **kwargs)
        return res
    return wrapper

def get_cm(cm):
    s = '$\\left( \\begin{smallmatrix} '
    for i, r in enumerate(cm):
        s += ' & '.join(map(str, r)) + ' \\\\ ' if i < len(cm)-1 else ' & '.join(map(str, r))
    s += ' \\end{smallmatrix} \\right)$'
    return s

# @print_params
def predict(lab, ba, cols, estimator, gs=None, evaluate_on_all=False, channels=CHANNEL_NAMES, selector=None, 
            print_incorrectly_predicted=False, show_selected=False, seed=213, eval_cv=True):
    df, df_bef, df_aft = prepare_dfs('all')
    if cols is None:
        df = df.loc[(slice(None), slice(ba)), channels]
    else:
        df = df.loc[(slice(None), slice(ba)), (channels, (cols))]
    X = df
    # X.columns = df.columns.droplevel(1)
    # X = X.drop(metapkl.columns, axis=1, errors='ignore')
    y = X.join(metapkl)[lab]
    X = X[y.isin([-1, 1])]
    y = y[y.isin([-1, 1])]
     
    if selector is not None:
        X = selector.fit_transform(X, y)
        if show_selected and hasattr(selector, 'get_support'):
            # print('(\'' + '\', \''.join(np.unique(df.columns.values[selector.get_support()])) + '\')')
            print(list(df.columns.values[selector.get_support()]))
            
    if gs is not None:
        gs = gs.fit(X, y)
        estimator = gs.best_estimator_
     
    if eval_cv:
        unique, counts = np.unique(y, return_counts=True)
        print('Class distribution: ', dict(zip(unique, counts)))
        scoring = ['accuracy', 'precision_weighted', 'recall_weighted', 'f1_weighted']
        scores = cross_validate(estimator, X, y, cv=5, scoring=scoring, return_train_score=False)
        print("Accuracy: %0.2f (+/- %0.2f)" % (scores['test_'+scoring[0]].mean(), scores['test_'+scoring[0]].std()))
        print("Precision: %0.2f (+/- %0.2f)" % (scores['test_'+scoring[1]].mean(), scores['test_'+scoring[1]].std()))
        print("Recall: %0.2f (+/- %0.2f)" % (scores['test_'+scoring[2]].mean(), scores['test_'+scoring[2]].std()))
        print("F1: %0.2f (+/- %0.2f)" % (scores['test_'+scoring[3]].mean(), scores['test_'+scoring[3]].std()))
        print(
            '{: <3.2f} $\pm$ {:<3.2f} & {: <3.2f} $\pm$ {: <3.2f} & '.format(scores['test_'+scoring[0]].mean(), scores['test_'+scoring[0]].std(), 
                                                                            scores['test_'+scoring[1]].mean(), scores['test_'+scoring[1]].std()) +
            '{: <3.2f} $\pm$ {:<3.2f} & {: <3.2f} $\pm$ {: <3.2f} & '.format(scores['test_'+scoring[2]].mean(), scores['test_'+scoring[2]].std(),
                                                                            scores['test_'+scoring[3]].mean(), scores['test_'+scoring[3]].std()) +
            ' \\\\ \hline'
        )
        
    else:
        X_train, X_test, y_train, y_test = \
            train_test_split(
                X, y, test_size=0.3, random_state=seed)

        unique, counts = np.unique(y_train, return_counts=True)
        print('Training distribution: ', dict(zip(unique, counts)))
        unique, counts = np.unique(y_test, return_counts=True)
        print('Testing distribution: ', dict(zip(unique, counts)))
        y_train = y_train.astype('int')
        estimator = estimator.fit(X_train, y_train)
        y_pred = estimator.predict(X_test)
        y_pred = y_pred.astype('int')
        y_test = y_test.astype('int')
        print("Accuracy score: %.2f" % metrics.accuracy_score(y_test, y_pred))
        print('Confusion matrix:\n', metrics.confusion_matrix(y_test, y_pred))
        print('Precision score: ', metrics.precision_score(y_test, y_pred, average='weighted'))
        print('Recall score: ', metrics.recall_score(y_test, y_pred, average='weighted'))
        print('f1 score: ', metrics.f1_score(y_test, y_pred, average='weighted'))
        print('ROC AUC score: ', metrics.roc_auc_score(y_test, y_pred, average='weighted'))
        # print('Coefficients: \n', np.array(X.stack().columns)[estimator.support_])
        # print(
        #     '{:.2f} & {:.2f} & {:.2f} & {} & {} \\\\ \hline'.format(
        #         metrics.accuracy_score(y_test, y_pred),
        #         metrics.f1_score(y_test, y_pred, average='weighted'),
        #         metrics.roc_auc_score(y_test, y_pred, average='weighted'),
        #         get_cm(metrics.confusion_matrix(y_test, y_pred)),
        #         ', '.join(channels)
        #     ))
    
    if print_incorrectly_predicted:
        y_pred_s = pd.Series(y_pred, index=y_test.index)
        print('Incorrectly predicted:')
        print(pd.DataFrame(y_test[y_pred != y_test]).join(X))
    
    if evaluate_on_all:
        y_pred = estimator.predict(X)
        y_pred = y_pred.astype('int')

        print("Accuracy score: %.2f" % metrics.accuracy_score(y, y_pred))
        print('Confusion matrix:\n', metrics.confusion_matrix(y, y_pred))
        print('Precision score: ', metrics.precision_score(y, y_pred, average='weighted'))
        print('Recall score: ', metrics.recall_score(y, y_pred, average='weighted'))
        print('f1 score: ', metrics.f1_score(y, y_pred, average='weighted'))
        print('ROC AUC score: ', metrics.roc_auc_score(y, y_pred, average='weighted'))
        if print_incorrectly_predicted:
            y_pred_s = pd.Series(y_pred, index=y.index)
            print('Incorrectly predicted:')
            print(pd.DataFrame(y[y_pred != y]).join(X))
    return estimator

def scorer(estimator, X, y):
    y_pred = estimator.predict(X)
    # return metrics.accuracy_score(y, y_pred)
    # return (metrics.f1_score(y, y_pred, average='weighted', labels=np.unique(y_pred)))
            # + metrics.precision_score(y, y_pred, average='weighted') 
            # + metrics.recall_score(y, y_pred, average='weighted') 
            # + metrics.accuracy_score(y, y_pred))
    return metrics.roc_auc_score(y, y_pred, average='weighted')

/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/sklearn/grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


In [8]:
from itertools import combinations

estimators = {
    svm.SVC(kernel='linear', class_weight='balanced'): {
        'C': [0.02, 0.5, 1.0, 1.5, 2, 3, 4, 5, 10, 50],
        'kernel': ('linear', 'poly', 'rbf'),
        # 'decision_function_shape' : ('ovo', 'ovr'),
    },
    LogisticRegression(class_weight='balanced'): {
        'C': [0.02, 0.5, 1.0, 2, 3, 4, 5, 10, 20, 50],
        'penalty': ['l2', 'l1'],
    },
}

for estimator, params in estimators.items():
    # for cols in (('lyap',),):
    # for cols in (('dfa', 'higu', 'hurst'), ('dfa',), ('higu',), ('hurst'), ('dfa', 'hurst')):
    for cols in combinations(('corr',), 1):
    # for cols in (('alpha',), ('beta',), ('gamma',), ('delta',), ('theta',),):
    # for cols in (('dfa',), ('dfa', 'lyap'), ('dfa', 'sampen'), ('dfa', 'corr')):
        for selector_name, selector in {
            'RFECV': RFECV(estimator), 
            'SelectFromModel': SelectFromModel(estimator), 
            'SelectKBest': SelectKBest(chi2, 3),
            'Genetic': GeneticSelectionCV(estimator,
                                      cv=5,
                                      verbose=0,
                                      scoring=scorer,
                                      n_population=80,
                                      crossover_proba=0.8,
                                      mutation_proba=0.2,
                                      n_generations=80,
                                      crossover_independent_proba=0.5,
                                      mutation_independent_proba=0.05,
                                      tournament_size=5,
                                      caching=True,
                                      n_jobs=-1,
                                      max_features=8),}.items():
            print(cols)
            print(selector_name)
            gs = grid_search.GridSearchCV(estimator, params, iid=False, scoring=scorer, cv=5)
            predict('dep', None, cols, estimator, gs=gs, show_selected=True, selector=selector)
            print(gs.best_params_)
            print('\n\n')

('corr',)
RFECV
[('Pz', 'corr')]


/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


Class distribution:  {-1: 50, 1: 49}
Accuracy: 0.55 (+/- 0.08)
Precision: 0.56 (+/- 0.11)
Recall: 0.55 (+/- 0.08)
F1: 0.51 (+/- 0.11)
0.55 $\pm$ 0.08 & 0.56 $\pm$ 0.11 & 0.55 $\pm$ 0.08 & 0.51 $\pm$ 0.11 &  \\ \hline
{'C': 4, 'kernel': 'rbf'}



('corr',)
SelectFromModel
[('FP1', 'corr'), ('FP2', 'corr'), ('C4', 'corr'), ('P3', 'corr'), ('O2', 'corr'), ('F7', 'corr'), ('F8', 'corr'), ('T4', 'corr'), ('T6', 'corr'), ('Cz', 'corr'), ('Pz', 'corr')]


/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


Class distribution:  {-1: 50, 1: 49}
Accuracy: 0.54 (+/- 0.05)
Precision: 0.55 (+/- 0.05)
Recall: 0.54 (+/- 0.05)
F1: 0.51 (+/- 0.08)
0.54 $\pm$ 0.05 & 0.55 $\pm$ 0.05 & 0.54 $\pm$ 0.05 & 0.51 $\pm$ 0.08 &  \\ \hline
{'C': 0.02, 'kernel': 'rbf'}



('corr',)
SelectKBest
[('FP1', 'corr'), ('C4', 'corr'), ('Pz', 'corr')]


/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


KeyboardInterrupt: 

# CROSS-VALIDATED

In [27]:
estimators = [
    # LogisticRegression(class_weight='balanced'),
    svm.SVC(C=1, class_weight='balanced', kernel='linear'),
]
# 74
channels = [('C4', 'lyap'), ('T3', 'lyap'), ('T6', 'lyap'), ('Pz', 'lyap'), ('C3', 'dfa'), ('P4', 'dfa')]
channels = [('F3', 'lyap'), ('F7', 'lyap'), ('T6', 'lyap'), ('O1', 'corr'), ('O2', 'corr'), ('T5', 'corr')]
# 73
# channels = [('P3', 'lyap'), ('T3', 'lyap'), ('T6', 'lyap'), ('Pz', 'lyap'), ('C3', 'hurst'), ('T3', 'hurst')] # C=50
# channels = [('T6', 'lyap'), ('Fz', 'lyap'), ('O2', 'sampen'), ('T6', 'sampen'), ('P4', 'dfa')]
channels = [('F3', 'corr'), ('Fz', 'corr'), ('P3', 'higu'), ('Cz', 'higu')]

for estimator in estimators:
    est = predict('dep', None, None, estimator, channels=channels)

Class distribution:  {-1: 49, 1: 48}
Accuracy: 0.63 (+/- 0.13)
Precision: 0.65 (+/- 0.15)
Recall: 0.63 (+/- 0.13)
F1: 0.62 (+/- 0.12)
0.63 $\pm$ 0.13 & 0.65 $\pm$ 0.15 & 0.63 $\pm$ 0.13 & 0.62 $\pm$ 0.12 &  \\ \hline


/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


In [6]:
estimators = [
    # LogisticRegression(class_weight='balanced'),
    svm.SVC(C=0.5, class_weight='balanced', kernel='linear'),
]
# 72
channels = [('T3', 'lyap'), ('T5', 'lyap'), ('T6', 'lyap'), ('Pz', 'lyap')]

for estimator in estimators:
    est = predict('dep', None, None, estimator, channels=channels)

Class distribution:  {-1: 49, 1: 48}
Accuracy: 0.72 (+/- 0.04)
Precision: 0.73 (+/- 0.04)
Recall: 0.72 (+/- 0.04)
F1: 0.72 (+/- 0.04)
0.72 $\pm$ 0.04 & 0.73 $\pm$ 0.04 & 0.72 $\pm$ 0.04 & 0.72 $\pm$ 0.04 &  \\ \hline


/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


In [32]:
estimators = [
    # LogisticRegression(class_weight='balanced'),
    svm.SVC(C=1, class_weight='balanced', kernel='linear'),
]
# 71
channels = [('F3', 'corr'), ('C4', 'corr'), ('P3', 'corr'), 
            ('F8', 'corr'), ('T5', 'corr'), ('T6', 'corr'), ('Fz', 'corr'), ('Cz', 'corr')]

for estimator in estimators:
    est = predict('dep', None, None, estimator, show_selected=True, channels=channels)

Class distribution:  {-1: 49, 1: 48}
Accuracy: 0.71 (+/- 0.05)
Precision: 0.72 (+/- 0.05)
Recall: 0.71 (+/- 0.05)
F1: 0.71 (+/- 0.05)


/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


In [32]:
estimators = [
    LogisticRegression(C=2, penalty='l2', class_weight='balanced'),
    # svm.SVC(C=1, class_weight='balanced', kernel='linear'),
]

# 67
channels = [('F8', 'dfa'), ('O2', 'dfa'),]

for estimator in estimators:
    est = predict('dep', None, None, estimator, channels=channels)

Class distribution:  {-1: 49, 1: 48}
Accuracy: 0.67 (+/- 0.16)
Precision: 0.68 (+/- 0.17)
Recall: 0.67 (+/- 0.16)
F1: 0.67 (+/- 0.16)
0.67 $\pm$ 0.16 & 0.68 $\pm$ 0.17 & 0.67 $\pm$ 0.16 & 0.67 $\pm$ 0.16 &  \\ \hline


/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


In [31]:
estimators = [
    # LogisticRegression(C=2, penalty='l2', class_weight='balanced'),
    svm.SVC(C=3, class_weight='balanced', kernel='rbf'),
]

# 67
channels = [('C3', 'higu'), ('C4', 'higu'), ('P4', 'higu'), ('T6', 'higu'), ('Cz', 'higu')]

for estimator in estimators:
    est = predict('dep', None, None, estimator, channels=channels)

Class distribution:  {-1: 49, 1: 48}
Accuracy: 0.67 (+/- 0.11)
Precision: 0.67 (+/- 0.12)
Recall: 0.67 (+/- 0.11)
F1: 0.67 (+/- 0.11)
0.67 $\pm$ 0.11 & 0.67 $\pm$ 0.12 & 0.67 $\pm$ 0.11 & 0.67 $\pm$ 0.11 &  \\ \hline


/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


In [30]:
estimators = [
    LogisticRegression(C=1, penalty='l2', class_weight='balanced'),
    # svm.SVC(C=1, class_weight='balanced', kernel='linear'),
]

# 68
channels = [('C4', 'sampen'), ('O2', 'sampen'), ('T6', 'sampen'),]

for estimator in estimators:
    est = predict('dep', None, None, estimator, channels=channels)

Class distribution:  {-1: 49, 1: 48}
Accuracy: 0.68 (+/- 0.12)
Precision: 0.69 (+/- 0.12)
Recall: 0.68 (+/- 0.12)
F1: 0.68 (+/- 0.12)
0.68 $\pm$ 0.12 & 0.69 $\pm$ 0.12 & 0.68 $\pm$ 0.12 & 0.68 $\pm$ 0.12 &  \\ \hline


/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


In [33]:
estimators = [
    LogisticRegression(C=4, penalty='l2', class_weight='balanced'),
    # svm.SVC(C=1, class_weight='balanced', kernel='linear'),
]

# 67
channels = [('O2', 'hurst'), ('T4', 'hurst'),]

for estimator in estimators:
    est = predict('dep', None, None, estimator, channels=channels)

Class distribution:  {-1: 49, 1: 48}
Accuracy: 0.67 (+/- 0.17)
Precision: 0.68 (+/- 0.18)
Recall: 0.67 (+/- 0.17)
F1: 0.67 (+/- 0.17)
0.67 $\pm$ 0.17 & 0.68 $\pm$ 0.18 & 0.67 $\pm$ 0.17 & 0.67 $\pm$ 0.17 &  \\ \hline


/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


In [29]:
channels = [('T3', 'lyap'), ('F4', 'lyap'), ('T6', 'lyap'), ('P3', 'lyap'), ('O2', 'lyap'), ('Pz', 'lyap')]
channels = [('F3', 'higu'), ('C3', 'higu'), ('C3', 'higu'), ('C4', 'higu'), ('P4', 'higu'), ('T6', 'higu'), ('Cz', 'higu'),]
channels = [('C4', 'sampen'), ('O2', 'sampen'), ('T6', 'sampen'),]
channels = [('F8', 'hurst'), ('O2', 'hurst'), ('T6', 'hurst'), ('T4', 'hurst'),]

channels = [('P3', 'lyap'), ('T3', 'lyap'), ('T6', 'lyap'), ('Pz', 'lyap'), ('C3', 'hurst'), ('T3', 'hurst')]
channels = [('T6', 'lyap'), ('Fz', 'lyap'), ('O2', 'sampen'), ('T6', 'sampen'), ('P4', 'dfa')]
channels = [('F3', 'corr'), ('Fz', 'corr'), ('P3', 'higu'), ('Cz', 'higu')]
channels = [('F3', 'corr'), ('C4', 'corr'), ('P3', 'corr'), 
            ('F8', 'corr'), ('T5', 'corr'), ('T6', 'corr'), ('Fz', 'corr'), ('Cz', 'corr')]

estimators = {
    svm.SVC(kernel='linear', class_weight='balanced'): {
        'C': [0.02, 0.5, 1.0, 1.5, 2, 3, 4, 5, 10, 50],
        'kernel': ('linear', 'poly', 'rbf'),
        # 'decision_function_shape' : ('ovo', 'ovr'),
    },
    LogisticRegression(class_weight='balanced'): {
        'C': [0.02, 0.5, 1.0, 2, 3, 4, 5, 10, 20, 50],
        'penalty': ['l2', 'l1'],
    },
}

for estimator, params in estimators.items():
    gs = grid_search.GridSearchCV(estimator, params, iid=False, scoring=scorer, cv=5)
    selector = GeneticSelectionCV(estimator,
                                      cv=5,
                                      verbose=0,
                                      scoring=scorer,
                                      n_population=80,
                                      crossover_proba=0.8,
                                      mutation_proba=0.2,
                                      n_generations=80,
                                      crossover_independent_proba=0.5,
                                      mutation_independent_proba=0.05,
                                      tournament_size=5,
                                      caching=True,
                                      n_jobs=-1)
    est = predict('dep', None, None, estimator, show_selected=True, channels=channels, gs=gs, selector=selector)
    print(gs.best_params_)

/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


[('F3', 'corr'), ('C4', 'corr'), ('P3', 'corr'), ('F8', 'corr'), ('T5', 'corr'), ('T6', 'corr'), ('Fz', 'corr'), ('Cz', 'corr')]
Class distribution:  {-1: 49, 1: 48}
Accuracy: 0.71 (+/- 0.05)
Precision: 0.72 (+/- 0.05)
Recall: 0.71 (+/- 0.05)
F1: 0.71 (+/- 0.05)
0.71 $\pm$ 0.05 & 0.72 $\pm$ 0.05 & 0.71 $\pm$ 0.05 & 0.71 $\pm$ 0.05 &  \\ \hline
{'C': 1.0, 'kernel': 'linear'}


/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


[('F3', 'corr'), ('C4', 'corr'), ('F8', 'corr'), ('T5', 'corr'), ('Fz', 'corr'), ('Cz', 'corr')]
Class distribution:  {-1: 49, 1: 48}
Accuracy: 0.69 (+/- 0.07)
Precision: 0.70 (+/- 0.08)
Recall: 0.69 (+/- 0.07)
F1: 0.69 (+/- 0.07)
0.69 $\pm$ 0.07 & 0.70 $\pm$ 0.08 & 0.69 $\pm$ 0.07 & 0.69 $\pm$ 0.07 &  \\ \hline
{'C': 3, 'penalty': 'l2'}


# Healthy below 10, depressed above 30 (26 / 30)

## Hurst exponent

In [69]:
estimator = LogisticRegression(C=3.5, penalty='l2', class_weight='balanced')
predict('dep', None, ('hurst',), estimator, channels=('O1', 'T4'))

Training distribution:  {-1: 20, 1: 19}
Testing distribution:  {-1: 6, 1: 11}
Accuracy score: 0.53
Confusion matrix:
 [[5 1]
 [7 4]]
Precision score:  0.6647058823529413
Recall score:  0.5294117647058824
f1 score:  0.5196078431372549
ROC AUC score:  0.5984848484848485
Accuracy: 0.65 (+/- 0.28)


LogisticRegression(C=3.5, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

## DFA

In [70]:
estimator = LogisticRegression(C=3.5, penalty='l2', class_weight='balanced')
# predict('dep', None, ('dfa',), estimator, channels=('O1', 'T4')) # DFA_4_300_11
# predict('dep', None, ('dfa',), estimator, channels=('F3', 'C3', 'C4', 'O1', 'T4', 'Pz')) # DFA_4_300_11_offset
predict('dep', None, ('dfa',), estimator, channels=('C3', 'C4', 'O1', 'T4')) # DFA_4_300_11_offset

Training distribution:  {-1: 20, 1: 19}
Testing distribution:  {-1: 6, 1: 11}
Accuracy score: 0.53
Confusion matrix:
 [[5 1]
 [7 4]]
Precision score:  0.6647058823529413
Recall score:  0.5294117647058824
f1 score:  0.5196078431372549
ROC AUC score:  0.5984848484848485
Accuracy: 0.72 (+/- 0.34)


LogisticRegression(C=3.5, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

## Correlation dimension

In [71]:
estimator = svm.SVC(C=0.02, kernel='poly', decision_function_shape='ovo', class_weight='balanced', shrinking=True)
predict('dep', None, ('corr',), estimator, channels=('F3', 'F4', 'P3', 'O1', 'T4', 'T5', 'Cz', 'Pz'))

Training distribution:  {-1: 20, 1: 19}
Testing distribution:  {-1: 6, 1: 11}
Accuracy score: 0.35
Confusion matrix:
 [[4 2]
 [9 2]]
Precision score:  0.4321266968325792
Recall score:  0.35294117647058826
f1 score:  0.3211558307533539
ROC AUC score:  0.4242424242424243
Accuracy: 0.62 (+/- 0.22)


SVC(C=0.02, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

## Lyapunov exponent
I was unable to create a classifier with better than 65% acc., although the depression scores and LLE are clearly correlated.

In [72]:
estimator = svm.SVC(C=50, kernel='linear', decision_function_shape='ovo', class_weight='balanced')
predict('dep', None, ('lyap',), estimator, channels=('FP1', 'FP2', 'F4', 'C3', 'O1', 'T3', 'T6'))

Training distribution:  {-1: 20, 1: 19}
Testing distribution:  {-1: 6, 1: 11}
Accuracy score: 0.53
Confusion matrix:
 [[2 4]
 [4 7]]
Precision score:  0.5294117647058824
Recall score:  0.5294117647058824
f1 score:  0.5294117647058824
ROC AUC score:  0.48484848484848486
Accuracy: 0.64 (+/- 0.22)


SVC(C=50, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [73]:
estimator = svm.SVC(C=1, kernel='rbf', decision_function_shape='ovo', class_weight='balanced')
predict('dep', None, ('lyap',), estimator, channels=('T6',))

Training distribution:  {-1: 20, 1: 19}
Testing distribution:  {-1: 6, 1: 11}
Accuracy score: 0.47
Confusion matrix:
 [[3 3]
 [6 5]]
Precision score:  0.5220588235294118
Recall score:  0.47058823529411764
f1 score:  0.48173374613003095
ROC AUC score:  0.4772727272727273
Accuracy: 0.66 (+/- 0.24)


SVC(C=1, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

## Sample entropy

In [74]:
estimator = LogisticRegression(C=2, penalty='l2', class_weight='balanced')
predict('dep', None, ('sampen',), estimator, channels=('P3', 'P4', 'T5', 'T6'))

Training distribution:  {-1: 20, 1: 19}
Testing distribution:  {-1: 6, 1: 11}
Accuracy score: 0.53
Confusion matrix:
 [[4 2]
 [6 5]]
Precision score:  0.6033613445378152
Recall score:  0.5294117647058824
f1 score:  0.5359477124183006
ROC AUC score:  0.5606060606060607
Accuracy: 0.66 (+/- 0.16)


LogisticRegression(C=2, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

## Higuchi dimension
Bad, although, again, correlated

# Healthy below 12, depressed above 28 (56 / 51)
Correlation, DFA, Hurst preserve their performance to some extent. Hurst only 67%.

## Correlation dimension

In [7]:
estimator = LogisticRegression(C=0.5, penalty='l2', class_weight='balanced')
predict('dep', None, ('corr',), estimator, channels=('F3', 'F4', 'T3', 'T5', 'Fz', 'Cz'))

Training distribution:  {-1: 31, 1: 29}
Testing distribution:  {-1: 8, 1: 19}
Accuracy score: 0.70
Confusion matrix:
 [[ 7  1]
 [ 7 12]]
Precision score:  0.7977207977207977
Recall score:  0.7037037037037037
f1 score:  0.7163299663299663
ROC AUC score:  0.7532894736842105
Accuracy: 0.63 (+/- 0.12)


LogisticRegression(C=0.5, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

## DFA

In [8]:
estimator = svm.SVC(C=1.5, kernel='rbf', decision_function_shape='ovo', class_weight='balanced')
predict('dep', None, ('dfa',), estimator, channels=('O1', 'T5', 'T6'))

Training distribution:  {-1: 31, 1: 29}
Testing distribution:  {-1: 8, 1: 19}
Accuracy score: 0.52
Confusion matrix:
 [[ 6  2]
 [11  8]]
Precision score:  0.6675381263616558
Recall score:  0.5185185185185185
f1 score:  0.5304725415070243
ROC AUC score:  0.5855263157894737
Accuracy: 0.44 (+/- 0.16)


SVC(C=1.5, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

## Hurst exponent

In [9]:
estimator = svm.SVC(C=1.5, kernel='rbf', decision_function_shape='ovo', class_weight='balanced', shrinking=True)
predict('dep', None, ('hurst',), estimator, channels=('C4', 'P4', 'T4', 'T6', 'Cz'))

Training distribution:  {-1: 31, 1: 29}
Testing distribution:  {-1: 8, 1: 19}
Accuracy score: 0.67
Confusion matrix:
 [[ 3  5]
 [ 4 15]]
Precision score:  0.6547619047619047
Recall score:  0.6666666666666666
f1 score:  0.6598290598290597
ROC AUC score:  0.5822368421052632
Accuracy: 0.43 (+/- 0.39)


SVC(C=1.5, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

# Manual selection

## LLE

## Higuchi fractal dimension

In [44]:
estimators = {
    # svm.SVC(kernel='linear', class_weight='balanced'): {
    #     'C': [0.02, 0.5, 1.0, 1.5, 2, 3, 4, 5, 10, 50],
    #     'kernel': ('linear', 'poly', 'rbf'),
    #     # 'decision_function_shape' : ('ovo', 'ovr'),
    # },
    LogisticRegression(class_weight='balanced'): {
        'C': [0.02, 0.5, 1.0, 2, 3, 4, 5, 10, 20, 50],
        'penalty': ['l2', 'l1'],
    },
}
channels = ['T6']
for estimator, params in estimators.items():
    est = grid_search.GridSearchCV(estimator, params, iid=False, scoring=scorer, cv=4)
    est = predict('dep', None, ('higu',), est, show_selected=True, channels=channels, seed=213, eval_cv=False)

/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


Training distribution:  {-1: 51, 1: 48}
Testing distribution:  {-1: 22, 1: 21}
Accuracy score: 0.56
Confusion matrix:
 [[11 11]
 [ 8 13]]
Precision score:  0.5607405140758874
Recall score:  0.5581395348837209
f1 score:  0.5567025902817168
ROC AUC score:  0.5595238095238095


# # DFA

In [63]:
estimators = {
    # svm.SVC(kernel='linear', class_weight='balanced'): {
    #     'C': [0.02, 0.5, 1.0, 1.5, 2, 3, 4, 5, 10, 50],
    #     'kernel': ('linear', 'poly', 'rbf'),
    #     'decision_function_shape' : ('ovo', 'ovr'),
    # },
    LogisticRegression(class_weight='balanced'): {
        'C': [0.02, 0.5, 1.0, 2, 3, 4, 5, 10, 20, 50],
        'penalty': ['l2', 'l1'],
    },
}
seed = randint(0, 100000)
print('Seed: %s' % seed)
channels = ['T4']
for estimator, params in estimators.items():
    est = grid_search.GridSearchCV(estimator, params, iid=False, scoring=scorer, cv=4)
    est = predict('dep', None, ('dfa',), est, show_selected=True, channels=channels, seed=seed)

Seed: 14411
Training distribution:  {-1: 36, 1: 31}
Testing distribution:  {-1: 13, 1: 17}
Accuracy score: 0.70
Confusion matrix:
 [[ 8  5]
 [ 4 13]]
Precision score:  0.6981481481481481
Recall score:  0.7
f1 score:  0.6982857142857142
ROC AUC score:  0.6900452488687784


## Sample entropy

In [65]:
estimators = {
    # svm.SVC(kernel='linear', class_weight='balanced'): {
    #     'C': [0.02, 0.5, 1.0, 1.5, 2, 3, 4, 5, 10, 50],
    #     'kernel': ('linear', 'poly', 'rbf'),
    #     'decision_function_shape' : ('ovo', 'ovr'),
    # },
    LogisticRegression(class_weight='balanced'): {
        'C': [0.02, 0.5, 1.0, 2, 3, 4, 5, 10, 20, 50],
        'penalty': ['l2', 'l1'],
    },
}
seed = randint(0, 100000)
print('Seed: %s' % seed)
channels = ['T6']
for estimator, params in estimators.items():
    est = grid_search.GridSearchCV(estimator, params, iid=False, scoring=scorer, cv=4)
    est = predict('dep', None, ('sampen',), est, show_selected=True, channels=channels, seed=seed)

Seed: 67493
Training distribution:  {-1: 33, 1: 34}
Testing distribution:  {-1: 16, 1: 14}
Accuracy score: 0.77
Confusion matrix:
 [[12  4]
 [ 3 11]]
Precision score:  0.7688888888888888
Recall score:  0.7666666666666667
f1 score:  0.7669262143121988
ROC AUC score:  0.7678571428571428


## Hurst exponent

In [69]:
estimators = {
    # svm.SVC(kernel='linear', class_weight='balanced'): {
    #     'C': [0.02, 0.5, 1.0, 1.5, 2, 3, 4, 5, 10, 50],
    #     'kernel': ('linear', 'poly', 'rbf'),
    #     'decision_function_shape' : ('ovo', 'ovr'),
    # },
    LogisticRegression(class_weight='balanced'): {
        'C': [0.02, 0.5, 1.0, 2, 3, 4, 5, 10, 20, 50],
        'penalty': ['l2', 'l1'],
    },
}
seed = randint(0, 100000)
print('Seed: %s' % seed)
channels = ['T4']
for estimator, params in estimators.items():
    est = grid_search.GridSearchCV(estimator, params, iid=False, scoring=scorer, cv=4)
    est = predict('dep', None, ('hurst',), est, show_selected=True, channels=channels, seed=seed)

Seed: 32420
Training distribution:  {-1: 36, 1: 31}
Testing distribution:  {-1: 13, 1: 17}
Accuracy score: 0.70
Confusion matrix:
 [[ 8  5]
 [ 4 13]]
Precision score:  0.6981481481481481
Recall score:  0.7
f1 score:  0.6982857142857142
ROC AUC score:  0.6900452488687784


## Correlation dimension

In [34]:
estimators = {
    # svm.SVC(kernel='linear', class_weight='balanced'): {
    #     'C': [0.02, 0.5, 1.0, 1.5, 2, 3, 4, 5, 10, 50],
    #     'kernel': ('linear', 'poly', 'rbf'),
    #     'decision_function_shape' : ('ovo', 'ovr'),
    # },
    LogisticRegression(class_weight='balanced'): {
        'C': [0.02, 0.5, 1.0, 2, 3, 4, 5, 10, 20, 50],
        'penalty': ['l2', 'l1'],
    },
}
# 36622
channels = ['C3']
for estimator, params in estimators.items():
    # est = grid_search.GridSearchCV(estimator, params, iid=False, scoring=scorer, cv=4)
    est = predict('dep', None, ('corr',), estimator, show_selected=True, channels=channels)

Seed: 5648
Accuracy: 0.58 (+/- 0.14)
Precision: 0.59 (+/- 0.15)
Recall: 0.58 (+/- 0.14)
F1: 0.58 (+/- 0.15)


/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)
