In [1]:
%load_ext autoreload
%autoreload 2
%load_ext watermark
%watermark -v -n -m -p numpy,scipy,sklearn,pandas

Mon Dec 31 2018 

CPython 3.6.6
IPython 6.5.0

numpy 1.15.1
scipy 1.1.0
sklearn 0.19.1
pandas 0.23.4

compiler   : GCC 4.8.2 20140120 (Red Hat 4.8.2-15)
system     : Linux
release    : 4.9.0-7-amd64
machine    : x86_64
processor  : 
CPU cores  : 12
interpreter: 64bit


In [1]:
%matplotlib inline
import sys
import pandas as pd
import numpy as np
import seaborn as sns
import os
import nolds
import data
import mne

PROJ_ROOT = os.path.abspath(os.path.join(os.pardir))
DATA_ROOT = os.path.abspath(os.path.join(PROJ_ROOT, 'data'))
PROCESSED_ROOT = os.path.abspath(os.path.join(DATA_ROOT, 'processed'))
RAW_ROOT = os.path.abspath(os.path.join(DATA_ROOT, 'raw'))
LABELED_ROOT = os.path.abspath(os.path.join(DATA_ROOT, 'labeled'))
DURATIONS_ROOT = os.path.abspath(os.path.join(DATA_ROOT, 'durations'))
sys.path.append(os.path.join(PROJ_ROOT, 'src'))
CHANNEL_NAMES = ['FP1', 'FP2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2',
                 'F7', 'F8', 'T3', 'T4', 'T5', 'T6', 'Fz', 'Cz', 'Pz']
META_COLUMN_NAMES = ['freq', 'RESP_4W', 'RESP_FIN', 'REMISE_FIN', 'AGE', 'SEX', 'M_1',
       'M_4', 'M_F', 'délka léčby', 'lék 1', 'lék 2', 'lék 3', 'lék 4']
META_FILE_NAME = 'DEP-POOL_Final_144.xlsx'
meta_df = pd.read_excel(os.path.join(RAW_ROOT, META_FILE_NAME), index_col='ID', names=META_COLUMN_NAMES)

raw_fif = mne.io.read_raw_fif(os.path.join(PROCESSED_ROOT, '1a.fif'))
t = pd.DataFrame(raw_fif.get_data())
data = pd.DataFrame(np.transpose(t.values), columns=CHANNEL_NAMES)
data = np.transpose(data.values)
metapkl = pd.read_pickle(os.path.join(LABELED_ROOT, 'processed', 'meta', 'meta.pkl'))
metapkl

Opening raw data file /home/kovar/thesis_project/data/processed/1a.fif...
This filename (/home/kovar/thesis_project/data/processed/1a.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, raw.fif.gz, raw_sss.fif.gz or raw_tsss.fif.gz
Isotrak not found
    Range : 0 ... 19104 =      0.000 ...    76.416 secs
Ready.


<ipython-input-1-2bb109ef8967>:25: RuntimeWarning: This filename (/home/kovar/thesis_project/data/processed/1a.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, raw.fif.gz, raw_sss.fif.gz or raw_tsss.fif.gz
  raw_fif = mne.io.read_raw_fif(os.path.join(PROCESSED_ROOT, '1a.fif'))


resp b/a sex  age  sfreq    sc  sc_bef  sc_aft  dep  dep_bef  \
patient trial                                                                
1       a        1   0   0   49    250  26.0      26      13    0        0   
        b        1   1   0   49    250  13.0      26      13   -1        0   
2       a        0   0   0   36    250  31.0      31      30    1        1   
        b        0   1   0   36    250  30.0      31      30    1        1   
3       a        1   0   0   48    250  25.0      25       7    0       -1   
        b        1   1   0   48    250   7.0      25       7   -1       -1   
4       a        0   0   0   55    250  26.0      26      25    0        0   
        b        0   1   0   55    250  25.0      26      25    0        0   
5       a        0   0   0   35    250  26.0      26      37    0        0   
        b        0   1   0   35    250  37.0      26      37    1        0   
6       a        0   0   0   37    250  31.0      31      17    1        1   
        b        0   1   0   37    250  17.0      31      17   -1        1   
7       a        0   0   0   63    250  30.0      30      25    1        1   
        b        0   1   0   63    250  25.0      30      25    0        1   
8       a        1   0   1   50    250  24.0      24      11    0       -1   
        b        1   1   1   50    250  11.0      24      11   -1       -1   
9       a        0   0   1   59    250  34.0      34      27    1        1   
        b        0   1   1   59    250  27.0      34      27    1        1   
10      a        1   0   0   49    250  36.0      36      17    1        1   
        b        1   1   0   49    250  17.0      36      17   -1        1   
11      a        0   0   1   53   1000  27.0      27      26    1        0   
        b        0   1   1   53   1000  26.0      27      26    0        0   
12      a        1   0   1   59   1000  30.0      30      12    1        1   
        b        1   1   1   59   1000  12.0      30      12   -1        1   
13      a        1   0   0   57    250  26.0      26       7    0        0   
        b        1   1   0   57    250   7.0      26       7   -1        0   
14      a        0   0   0   30    250  28.0      28      17    1        0   
        b        0   1   0   30    250  17.0      28      17   -1        0   
15      a        1   0   0   35   1000  25.0      25       3    0       -1   
        b        1   1   0   35   1000   3.0      25       3   -1       -1   
...            ...  ..  ..  ...    ...   ...     ...     ...  ...      ...   
119     a        1   0   1   61    250  23.0      23       4    0       -1   
        b        1   1   1   61    250   4.0      23       4   -1       -1   
120     a        0   0   0   41   1000  28.0      28      19    1        0   
        b        0   1   0   41   1000  19.0      28      19   -1        0   
121     a        0   0   0   34    250  24.0      24      26    0       -1   
        b        0   1   0   34    250  26.0      24      26    0       -1   
122     a        0   0   1   55    250  35.0      35      19    1        1   
        b        0   1   1   55    250  19.0      35      19   -1        1   
123     a        0   0   1   54    250  24.0      24      25    0       -1   
        b        0   1   1   54    250  25.0      24      25    0       -1   
124     a        0   0   0   52    250  30.0      30      23    1        1   
        b        0   1   0   52    250  23.0      30      23    0        1   
125     a        1   0   0   56    250  26.0      26      11    0        0   
        b        1   1   0   56    250  11.0      26      11   -1        0   
126     a        0   0   0   40    250  25.0      25      17    0       -1   
        b        0   1   0   40    250  17.0      25      17   -1       -1   
127     a        0   0   0   35    250  25.0      25      21    0       -1   
        b        0   1   0   35    250  21.0      25      21    0       -1   
128     a        1   0   0   51    2

In [2]:
def f(row, col):
    if row[col] <= 10:
        return -1
    if row[col] <= 30:
        return 0
    else:
        return 1
def ff(row, col, n=5):
    for i in range(n):
        if row[col] <= metapkl.quantile((i+1)/n)[col]:
            return i
    
metapkl['dep'] = metapkl.apply(lambda row: f(row, 'sc'), axis=1)
metapkl['dep_bef'] = metapkl.apply(lambda row: f(row, 'sc_bef'), axis=1)
metapkl['dep_aft'] = metapkl.apply(lambda row: f(row, 'sc_aft'), axis=1)
metapkl = metapkl.astype({'dep': 'category', 'dep_bef': 'category', 'dep_aft': 'category'})                                           
print(metapkl['dep'].value_counts())
print(metapkl['dep_bef'].value_counts())
print(metapkl['dep_aft'].value_counts())
def f(row, col):
    if row[col] <= metapkl.quantile(0.33)['change']:
        return -1
    if row[col] <= metapkl.quantile(0.66)['change']:
        return 0
    else:
        return 1
    
metapkl['resp'] = metapkl.apply(lambda row: f(row, 'change'), axis=1)
metapkl = metapkl.astype({'resp': 'category'})                                           
print(metapkl['resp'].value_counts())

 0    198
 1     34
-1     34
Name: dep, dtype: int64
0    208
1     58
Name: dep_bef, dtype: int64
 0    188
-1     68
 1     10
Name: dep_aft, dtype: int64
 1    90
 0    88
-1    88
Name: resp, dtype: int64


In [3]:
def prepare_dfs(col='lyap', kind='processed'):
    df = pd.read_pickle(os.path.join(LABELED_ROOT, kind, col, f'training_{col}.pkl')).dropna()
    df_bef = pd.read_pickle(os.path.join(LABELED_ROOT, kind, col, f'{col}_bef.pkl')).dropna()
    df_aft = pd.read_pickle(os.path.join(LABELED_ROOT, kind, col, f'{col}_aft.pkl')).dropna()
    return df, df_bef, df_aft
    
def prepare_resp_non(col='lyap'):
    df, df_bef, df_aft = prepare_dfs(col)
    return df[df['change'] >= df.quantile(0.66)['change']], df[df['change'] <= df.quantile(0.33)['change']]

def prepare_dep_non(col='lyap'):
    df, df_bef, df_aft = prepare_dfs(col)
    df = df.drop(metapkl.columns, axis=1, errors='ignore')
    df = df.join(metapkl)
    return df[df['dep'] == 1], df[df['dep'] == -1]

col = 'hurst'
df, df_bef, df_aft = prepare_dfs(col)
df_dep, df_nond = prepare_dep_non(col)
df_dep # There are only 3 patients who were not cured - not enough data
df_bef

/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


channel       FP1       FP2        F3        F4        C3        C4        P3  \
measure     hurst     hurst     hurst     hurst     hurst     hurst     hurst   
patient                                                                         
1        0.753999  0.769921  0.664204  0.797222  0.717136  0.670598  0.717158   
3        0.483106  0.553749  0.325695  0.478609  0.357043  0.346590  0.331214   
4        0.590308  0.541832  0.408367  0.522805  0.420881  0.421173  0.317976   
5        0.660602  0.671559  0.486952  0.552988  0.475865  0.490763  0.469610   
7        0.639096  0.639857  0.553844  0.554577  0.461236  0.365423  0.436752   
9        0.614442  0.635342  0.638403  0.622358  0.616017  0.606111  0.673701   
10       0.724055  0.739994  0.641489  0.592656  0.590430  0.590867  0.594284   
11       0.597459  0.661764  0.642293  0.652749  0.624995  0.705735  0.432528   
12       0.832184  0.744612  0.707344  0.625504  0.652221  0.723436  0.739239   
14       0.820025  0.836417  0.670636  0.695366  0.718106  0.751496  0.701602   
15       0.789668  0.768005  0.669128  0.662312  0.685437  0.673983  0.671491   
16       0.597817  0.607292  0.527661  0.557764  0.561065  0.602014  0.551127   
17       0.554936  0.557657  0.515685  0.485301  0.424117  0.467076  0.436336   
18       0.688870  0.655660  0.598123  0.583084  0.577431  0.542526  0.592951   
19       0.616511  0.631594  0.553669  0.593662  0.467794  0.432599  0.494526   
20       0.636589  0.675734  0.564011  0.459885  0.496038  0.471468  0.431317   
22       0.613727  0.660269  0.642280  0.636919  0.663253  0.578787  0.591345   
23       0.615167  0.661889  0.617417  0.590063  0.555753  0.569368  0.542934   
24       0.690701  0.670268  0.524618  0.589364  0.597560  0.539645  0.505840   
25       0.603308  0.591698  0.569239  0.552218  0.555800  0.563258  0.539206   
26       0.623602  0.662135  0.502522  0.550089  0.499895  0.496693  0.317475   
27       0.560730  0.592633  0.552116  0.527454  0.558303  0.506181  0.516698   
28       0.542512  0.490586  0.481522  0.413476  0.534348  0.468061  0.323943   
29       0.691098  0.700826  0.692508  0.626029  0.621230  0.579140  0.565149   
30       0.772660  0.791092  0.706712  0.759470  0.672674  0.649862  0.682524   
31       0.702028  0.687744  0.541059  0.553816  0.578532  0.489232  0.616714   
32       0.607256  0.563812  0.416201  0.500108  0.430466  0.387784  0.386542   
33       0.458505  0.453774  0.396653  0.367255  0.372247  0.408980  0.360121   
34       0.776192  0.846239  0.700580  0.659454  0.700208  0.697899  0.656419   
35       0.805447  0.799487  0.783529  0.814419  0.689170  0.671269  0.681100   
...           ...       ...       ...       ...       ...       ...       ...   
96       0.536939  0.517970  0.344031  0.359802  0.428282  0.316459  0.418508   
97       0.742351  0.725569  0.591421  0.568121  0.527010  0.525995  0.543318   
99       0.659493  0.658699  0.553942  0.572075  0.581594  0.585257  0.541289   
102      0.686641  0.718851  0.647651  0.591969  0.657447  0.706976  0.541668   
103      0.714121  0.680444  0.637762  0.620926  0.642751  0.606465  0.590615   
104      0.706643  0.694398  0.550952  0.570414  0.707609  0.689056  0.530546   
106      0.733267  0.804222  0.714299  0.765544  0.754832  0.735182  0.719914   
107      0.616948  0.667000  0.584419  0.600257  0.662906  0.606717  0.595170   
108      0.728199  0.703754  0.668563  0.710401  0.671483  0.667588  0.673620   
109      0.696116  0.746083  0.601951  0.626518  0.634062  0.627394  0.592787   
110      0.667357  0.673566  0.585908  0.621977  0.579194  0.611439  0.567259   
111      0.693586  0.673217  0.587229  0.623921  0.535108  0.692164  0.511676   
112      0.533819  0.584420  0.618539  0.704392  0.531402  0.555196  0.541591   
113      0.699318  0.737187  0.568881  0.564011  0.696660  0.500708  0.510231   
114      0.703606  0.767834  0.676271  0.696193  0.725792  0.703918  0.708411   
115      0.714991  0.751089  0.

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import (SelectFromModel, RFE, RFECV, SelectKBest, mutual_info_classif)
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm, grid_search, datasets
from genetic_selection import GeneticSelectionCV
from functools import wraps
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB

def print_params(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        print(f'{args} {kwargs}')
        res = f(*args, **kwargs)
        return res
    return wrapper

# @print_params
def predict(lab, ba, cols, estimator, evaluate_on_all=False, channels=CHANNEL_NAMES, selector=None, 
            print_incorrectly_predicted=False):
    df, df_bef, df_aft = prepare_dfs('all')
    df = df.loc[(slice(None), slice(ba)), (channels, (cols))]
    X = df
    # X.columns = df.columns.droplevel(1)
    X = X.drop(metapkl.columns, axis=1, errors='ignore')
    y = X.join(metapkl)[lab]
    X = X[y.isin([-1, 1])]
    y = y[y.isin([-1, 1])]
    
    if selector is not None:
        X = selector.transform(X)
    
    X_train, X_test, y_train, y_test = \
        train_test_split(
            X, y, test_size=0.3, random_state=213)
    
    # unique, counts = np.unique(y_train, return_counts=True) 
    # print(counts[0] / (counts[0] + counts[1]))
    unique, counts = np.unique(y_train, return_counts=True)
    print('Training distribution: ', dict(zip(unique, counts)))
    unique, counts = np.unique(y_test, return_counts=True)
    print('Testing distribution: ', dict(zip(unique, counts)))

    y_train = y_train.astype('int')

    estimator = estimator.fit(X_train, y_train)
    y_pred = estimator.predict(X_test)
    y_pred = y_pred.astype('int')
    y_test = y_test.astype('int')
    
    if hasattr(estimator, 'support_'):
        # print('Selected columns: ', X.columns.values[estimator.support_])
        pass
    print("Accuracy score: %.2f" % metrics.accuracy_score(y_test, y_pred))
    print('Confusion matrix:\n', metrics.confusion_matrix(y_test, y_pred))
    print('Precision score: ', metrics.precision_score(y_test, y_pred, average='weighted'))
    print('Recall score: ', metrics.recall_score(y_test, y_pred, average='weighted'))
    print('f1 score: ', metrics.f1_score(y_test, y_pred, average='weighted'))
    print('ROC AUC score: ', metrics.roc_auc_score(y_test, y_pred, average='weighted'))
    # print('Coefficients: \n', np.array(X.stack().columns)[estimator.support_])
    
    if print_incorrectly_predicted:
        y_pred_s = pd.Series(y_pred, index=y_test.index)
        print('Incorrectly predicted:')
        print(pd.DataFrame(y_test[y_pred != y_test]).join(X))
    
    if evaluate_on_all:
        y_pred = estimator.predict(X)
        y_pred = y_pred.astype('int')

        print("Accuracy score: %.2f" % metrics.accuracy_score(y, y_pred))
        print('Confusion matrix:\n', metrics.confusion_matrix(y, y_pred))
        print('Precision score: ', metrics.precision_score(y, y_pred, average='weighted'))
        print('Recall score: ', metrics.recall_score(y, y_pred, average='weighted'))
        print('f1 score: ', metrics.f1_score(y, y_pred, average='weighted'))
        print('ROC AUC score: ', metrics.roc_auc_score(y, y_pred, average='weighted'))
        if print_incorrectly_predicted:
            y_pred_s = pd.Series(y_pred, index=y.index)
            print('Incorrectly predicted:')
            print(pd.DataFrame(y[y_pred != y]).join(X))
    return estimator


def scorer(estimator, X, y):
    y_pred = estimator.predict(X)
    # return metrics.accuracy_score(y, y_pred)
    # return (metrics.f1_score(y, y_pred, average='weighted', labels=np.unique(y_pred)))
            # + metrics.precision_score(y, y_pred, average='weighted') 
            # + metrics.recall_score(y, y_pred, average='weighted') 
            # + metrics.accuracy_score(y, y_pred))
    return metrics.roc_auc_score(y, y_pred, average='weighted')

In [41]:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

estimator_svc = grid_search.GridSearchCV(svm.SVC(class_weight='balanced'), {
    'C': [0.02, 0.5, 1.0, 1.5, 2],
    # 'kernel': ('linear', 'poly', 'rbf', 'sigmoid'),
    'shrinking': (True, False),
    # 'decision_function_shape' : ('ovo', 'ovr'),
}, iid=False, scoring=scorer)

estimator_lg = grid_search.GridSearchCV(LogisticRegression(class_weight='balanced'), {
    'C': [0.5, 1.0, 1.5, 2, 2.5, 3, 3.5],
    'penalty': ['l2', 'l1'],
}, iid=False, scoring=scorer)

estimators = {
    svm.SVC(class_weight='balanced'): {
        'C': [0.02, 0.5, 1.0, 1.5, 2],
        # 'kernel': ('linear', 'poly', 'rbf', 'sigmoid'),
        'shrinking': (True, False),
        # 'decision_function_shape' : ('ovo', 'ovr'),
    },
    LogisticRegression(class_weight='balanced'): {
        'C': [0.5, 1.0, 1.5, 2, 2.5, 3, 3.5],
        'penalty': ['l2', 'l1'],
    }
}

estimators = {
    svm.SVC(kernel='linear', class_weight='balanced') : {},
    # LogisticRegression(C=1, class_weight='balanced') : {},
}

cols = ('lyap', 'corr', 'dfa', 'sampen')

for estimator, params in estimators.items():
    # for cols in (('dfa', 'higu'),):
    # for cols in (('dfa', 'higu', 'hurst'), ('dfa',), ('higu',), ('hurst'), ('dfa', 'hurst')):
    for cols in (('dfa', 'higu', 'hurst', 'sampen', 'lyap'), ('dfa',), ('higu',), ('hurst',), ('sampen',), ('lyap',)):
    # for cols in (('dfa',), ('dfa', 'lyap'), ('dfa', 'sampen'), ('dfa', 'corr')):
        for selector in (GeneticSelectionCV(estimator,
                                          cv=3,
                                          verbose=0,
                                          scoring=scorer,
                                          n_population=50,
                                          crossover_proba=0.8,
                                          mutation_proba=0.2,
                                          n_generations=50,
                                          crossover_independent_proba=0.5,
                                          mutation_independent_proba=0.05,
                                          tournament_size=3,
                                          caching=True,
                                          n_jobs=-1),):
            # selector = grid_search.GridSearchCV(selector, params, iid=False, scoring=scorer)
            predict('resp', None, cols, selector)
            # predict('dep_bef', 'a', cols, selector.estimator.estimator)
            # predict('dep_aft', 'b', cols, selector)
            # predict('resp', 'b', cols, selector)

Training distribution:  {-1: 51, 1: 47}
Testing distribution:  {-1: 23, 1: 19}
Accuracy score: 0.45
Confusion matrix:
 [[10 13]
 [10  9]]
Precision score:  0.4588744588744589
Recall score:  0.4523809523809524
f1 score:  0.4533128055533047
ROC AUC score:  0.454233409610984
Training distribution:  {-1: 51, 1: 47}
Testing distribution:  {-1: 23, 1: 19}
Accuracy score: 0.60
Confusion matrix:
 [[15  8]
 [ 9 10]]
Precision score:  0.5935846560846562
Recall score:  0.5952380952380952
f1 score:  0.5940743174785729
ROC AUC score:  0.5892448512585812
Training distribution:  {-1: 51, 1: 47}
Testing distribution:  {-1: 23, 1: 19}
Accuracy score: 0.45
Confusion matrix:
 [[ 0 23]
 [ 0 19]]
Precision score:  0.2046485260770975
Recall score:  0.4523809523809524
f1 score:  0.2818110850897736
ROC AUC score:  0.5
Training distribution:  {-1: 51, 1: 47}
Testing distribution:  {-1: 23, 1: 19}
Accuracy score: 0.50
Confusion matrix:
 [[ 3 20]
 [ 1 18]]
Precision score:  0.625
Recall score:  0.5
f1 score:  0.

# Depressed / Nondepressed

## Lyap

In [35]:
# dfa_def, L 10, H 30, 88
estimator = svm.SVC(kernel='linear', class_weight='balanced')
selector = GeneticSelectionCV(
    estimator,
    cv=3,
    verbose=0,
    scoring=scorer,
    n_population=50,
    crossover_proba=0.8,
    mutation_proba=0.2,
    n_generations=50,
    crossover_independent_proba=0.5,
    mutation_independent_proba=0.05,
    tournament_size=3,
    caching=True,
    n_jobs=-1)
selector = predict('dep', None, ('lyap'), selector, evaluate_on_all=True)

Training distribution:  {-1: 15, 1: 24}
Testing distribution:  {-1: 11, 1: 6}


/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


Accuracy score: 0.53
Confusion matrix:
 [[4 7]
 [1 5]]
Precision score:  0.6647058823529413
Recall score:  0.5294117647058824
f1 score:  0.5196078431372549
ROC AUC score:  0.5984848484848485
Accuracy score: 0.75
Confusion matrix:
 [[17  9]
 [ 5 25]]
Precision score:  0.752673796791444
Recall score:  0.75
f1 score:  0.7473958333333333
ROC AUC score:  0.7435897435897437


In [26]:
estimator = svm.SVC(kernel='linear', class_weight='balanced')
estimator = predict('dep', None, ('lyap',), estimator, evaluate_on_all=True, 
                    channels=('F3', 'F4', 'FP2'), print_incorrectly_predicted=True)
estimator

Training distribution:  {-1: 29, 1: 33}
Testing distribution:  {-1: 11, 1: 16}
Accuracy score: 0.67
Confusion matrix:
 [[ 5  6]
 [ 3 13]]
Precision score:  0.6600877192982456
Recall score:  0.6666666666666666
f1 score:  0.6546365914786968
Incorrectly predicted:
               dep  (FP2, lyap)  (F3, lyap)  (F4, lyap)
patient trial                                          
106     a        1     8.217972    9.394106    9.039179
36      b       -1    11.363785   11.071076   11.037363
103     b       -1    10.071514   10.692004   10.524601
113     b        1     8.071585    9.121098    6.944322
107     b       -1     8.880156   10.363891    9.807452
130     a        1     8.956714    9.002172    9.214503
3       b       -1    11.302472   11.271126   11.381274
75      b       -1    11.019301   10.931988   11.019289
115     b       -1    10.337421   10.198964   10.465757
Accuracy score: 0.58
Confusion matrix:
 [[22 18]
 [19 30]]
Precision score:  0.5852630857769252
Recall score:  0.584269662

/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)
/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (1 levels on the left, 2 on the right)
  warnings.warn(msg, UserWarning)
/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (1 levels on the left, 2 on the right)
  warnings.warn(msg, UserWarning)


SVC(C=1.0, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

## DFA

In [10]:
# L 12, H 28
estimator = svm.SVC(kernel='linear', class_weight='balanced')
estimator = predict('dep', None, ('dfa',), estimator, evaluate_on_all=True, 
                    channels=('T4', 'T5', 'T6', 'Cz', 'O1'), print_incorrectly_predicted=True) # DFA_def
# estimator = predict('dep', None, ('dfa',), estimator, evaluate_on_all=False, 
#                     channels=('Fz',), print_incorrectly_predicted=False) # DFA_arit_no_overlap
estimator

Training distribution:  {-1: 15, 1: 24}
Testing distribution:  {-1: 11, 1: 6}
Accuracy score: 0.53
Confusion matrix:
 [[3 8]
 [0 6]]
Precision score:  0.7983193277310924
Recall score:  0.5294117647058824
f1 score:  0.48907563025210077
Incorrectly predicted:
               dep  (O1, dfa)  (T4, dfa)  (T5, dfa)  (T6, dfa)  (Cz, dfa)
patient trial                                                            
3       b       -1   0.243963   0.466208   0.369881   0.283775   0.350899
75      b       -1   0.437848   0.787615   0.491093   0.491635   0.669573
63      b       -1   0.686631   0.578315   0.540581   0.544454   0.570220
111     b       -1   0.712939   0.599738   0.391483   0.486671   0.455653
115     b       -1   0.470486   0.663665   0.509812   0.508774   0.630070
97      b       -1   0.557046   0.718987   0.521811   0.488559   0.644719
77      b       -1   0.156859   0.309606   0.425798   0.414859   0.566363
23      b       -1   0.623567   0.704339   0.551867   0.573251   0.554170
Ac

/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)
/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (1 levels on the left, 2 on the right)
  warnings.warn(msg, UserWarning)
/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (1 levels on the left, 2 on the right)
  warnings.warn(msg, UserWarning)


SVC(C=1.0, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [11]:
gs = grid_search.GridSearchCV(estimator, {
    'C': np.arange(0.5, 10, 0.5),
    'kernel': ('linear', 'poly', 'rbf', 'sigmoid'),
    'degree': [2, 3, 4, 5],
    'shrinking': (True, False),
    'decision_function_shape' : ('ovo', 'ovr'),
    'class_weight' : ['balanced', {-1: 1, 1: 1.2}]
}, scoring=None)

predict('dep', None, ('dfa'), gs, evaluate_on_all=False, channels=('T4', 'T5', 'T6', 'Cz', 'O1'))

/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


Training distribution:  {-1: 15, 1: 24}
Testing distribution:  {-1: 11, 1: 6}
Accuracy score: 0.71
Confusion matrix:
 [[6 5]
 [0 6]]
Precision score:  0.839572192513369
Recall score:  0.7058823529411765
f1 score:  0.7058823529411764


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'C': array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5]), 'kernel': ('linear', 'poly', 'rbf', 'sigmoid'), 'degree': [2, 3, 4, 5], 'shrinking': (True, False), 'decision_function_shape': ('ovo', 'ovr'), 'class_weight': ['balanced', {-1: 1, 1: 1.2}]},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)

In [12]:
gs = grid_search.GridSearchCV(estimator, {
    'C': np.arange(0.5, 10, 0.5),
    'kernel': ('linear', 'poly', 'rbf', 'sigmoid'),
    'degree': [2, 3, 4, 5],
    'shrinking': (True, False),
    'decision_function_shape' : ('ovo', 'ovr'),
    'class_weight' : ['balanced', {-1: 1, 1: 1.2}]
})

predict('dep', None, ('lyap'), gs, evaluate_on_all=True, channels=('F3', 'F4', 'FP2')) #, channels=('T4', 'T5', 'T6', 'Cz', 'O1', 'O2'))
gs.best_params_

/home/kovar/miniconda3/envs/thesis/lib/python3.6/site-packages/pandas/core/reshape/merge.py:544: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


Training distribution:  {-1: 15, 1: 24}
Testing distribution:  {-1: 11, 1: 6}


KeyboardInterrupt: 