In [1]:
%load_ext autoreload
%autoreload 2
%load_ext watermark
%watermark -v -n -m -p numpy,scipy,sklearn,pandas

Sat Jan 05 2019 

CPython 3.6.6
IPython 6.5.0

numpy 1.15.1
scipy 1.1.0
sklearn 0.19.1
pandas 0.23.4

compiler   : GCC 4.8.2 20140120 (Red Hat 4.8.2-15)
system     : Linux
release    : 4.9.0-7-amd64
machine    : x86_64
processor  : 
CPU cores  : 12
interpreter: 64bit


In [2]:
%matplotlib inline
import sys
import pandas as pd
import numpy as np
import seaborn as sns
import os
import nolds
import data
import mne

PROJ_ROOT = os.path.abspath(os.path.join(os.pardir))
DATA_ROOT = os.path.abspath(os.path.join(PROJ_ROOT, 'data'))
PROCESSED_ROOT = os.path.abspath(os.path.join(DATA_ROOT, 'processed'))
RAW_ROOT = os.path.abspath(os.path.join(DATA_ROOT, 'raw'))
LABELED_ROOT = os.path.abspath(os.path.join(DATA_ROOT, 'labeled'))
DURATIONS_ROOT = os.path.abspath(os.path.join(DATA_ROOT, 'durations'))
sys.path.append(os.path.join(PROJ_ROOT, 'src'))
CHANNEL_NAMES = ['FP1', 'FP2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2',
                 'F7', 'F8', 'T3', 'T4', 'T5', 'T6', 'Fz', 'Cz', 'Pz']
META_COLUMN_NAMES = ['freq', 'RESP_4W', 'RESP_FIN', 'REMISE_FIN', 'AGE', 'SEX', 'M_1',
       'M_4', 'M_F', 'délka léčby', 'lék 1', 'lék 2', 'lék 3', 'lék 4']
META_FILE_NAME = 'DEP-POOL_Final_144.xlsx'
meta_df = pd.read_excel(os.path.join(RAW_ROOT, META_FILE_NAME), index_col='ID', names=META_COLUMN_NAMES)

raw_fif = mne.io.read_raw_fif(os.path.join(PROCESSED_ROOT, '75b.fif'))
t = pd.DataFrame(raw_fif.get_data())
data = pd.DataFrame(np.transpose(t.values), columns=CHANNEL_NAMES)
data = np.transpose(data.values)
metapkl = pd.read_pickle(os.path.join(LABELED_ROOT, 'processed', 'meta', 'meta.pkl'))
metapkl

Opening raw data file /home/kovar/thesis_project/data/processed/75b.fif...
This filename (/home/kovar/thesis_project/data/processed/75b.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, raw.fif.gz, raw_sss.fif.gz or raw_tsss.fif.gz
Isotrak not found
    Range : 0 ... 35665 =      0.000 ...   142.660 secs
Ready.


<ipython-input-2-2d4c74245861>:25: RuntimeWarning: This filename (/home/kovar/thesis_project/data/processed/75b.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, raw.fif.gz, raw_sss.fif.gz or raw_tsss.fif.gz
  raw_fif = mne.io.read_raw_fif(os.path.join(PROCESSED_ROOT, '75b.fif'))


resp b/a sex  age  sfreq    sc  sc_bef  sc_aft  dep  dep_bef  \
patient trial                                                                
1       a        1   0   0   49    250  26.0      26      13    0        0   
        b        1   1   0   49    250  13.0      26      13   -1        0   
2       a        0   0   0   36    250  31.0      31      30    1        1   
        b        0   1   0   36    250  30.0      31      30    1        1   
3       a        1   0   0   48    250  25.0      25       7    0       -1   
        b        1   1   0   48    250   7.0      25       7   -1       -1   
4       a        0   0   0   55    250  26.0      26      25    0        0   
        b        0   1   0   55    250  25.0      26      25    0        0   
5       a        0   0   0   35    250  26.0      26      37    0        0   
        b        0   1   0   35    250  37.0      26      37    1        0   
6       a        0   0   0   37    250  31.0      31      17    1        1   
        b        0   1   0   37    250  17.0      31      17   -1        1   
7       a        0   0   0   63    250  30.0      30      25    1        1   
        b        0   1   0   63    250  25.0      30      25    0        1   
8       a        1   0   1   50    250  24.0      24      11    0       -1   
        b        1   1   1   50    250  11.0      24      11   -1       -1   
9       a        0   0   1   59    250  34.0      34      27    1        1   
        b        0   1   1   59    250  27.0      34      27    1        1   
10      a        1   0   0   49    250  36.0      36      17    1        1   
        b        1   1   0   49    250  17.0      36      17   -1        1   
11      a        0   0   1   53   1000  27.0      27      26    1        0   
        b        0   1   1   53   1000  26.0      27      26    0        0   
12      a        1   0   1   59   1000  30.0      30      12    1        1   
        b        1   1   1   59   1000  12.0      30      12   -1        1   
13      a        1   0   0   57    250  26.0      26       7    0        0   
        b        1   1   0   57    250   7.0      26       7   -1        0   
14      a        0   0   0   30    250  28.0      28      17    1        0   
        b        0   1   0   30    250  17.0      28      17   -1        0   
15      a        1   0   0   35   1000  25.0      25       3    0       -1   
        b        1   1   0   35   1000   3.0      25       3   -1       -1   
...            ...  ..  ..  ...    ...   ...     ...     ...  ...      ...   
119     a        1   0   1   61    250  23.0      23       4    0       -1   
        b        1   1   1   61    250   4.0      23       4   -1       -1   
120     a        0   0   0   41   1000  28.0      28      19    1        0   
        b        0   1   0   41   1000  19.0      28      19   -1        0   
121     a        0   0   0   34    250  24.0      24      26    0       -1   
        b        0   1   0   34    250  26.0      24      26    0       -1   
122     a        0   0   1   55    250  35.0      35      19    1        1   
        b        0   1   1   55    250  19.0      35      19   -1        1   
123     a        0   0   1   54    250  24.0      24      25    0       -1   
        b        0   1   1   54    250  25.0      24      25    0       -1   
124     a        0   0   0   52    250  30.0      30      23    1        1   
        b        0   1   0   52    250  23.0      30      23    0        1   
125     a        1   0   0   56    250  26.0      26      11    0        0   
        b        1   1   0   56    250  11.0      26      11   -1        0   
126     a        0   0   0   40    250  25.0      25      17    0       -1   
        b        0   1   0   40    250  17.0      25      17   -1       -1   
127     a        0   0   0   35    250  25.0      25      21    0       -1   
        b        0   1   0   35    250  21.0      25      21    0       -1   
128     a        1   0   0   51    2

In [35]:
def f(row, col):
    if row[col] <= 10:
        return -1
    if row[col] <= 30:
        return 0
    else:
        return 1
def ff(row, col, n=5):
    for i in range(n):
        if row[col] <= metapkl.quantile((i+1)/n)[col]:
            return i
    
metapkl['dep'] = metapkl.apply(lambda row: f(row, 'sc'), axis=1)
metapkl['dep_bef'] = metapkl.apply(lambda row: f(row, 'sc_bef'), axis=1)
metapkl['dep_aft'] = metapkl.apply(lambda row: f(row, 'sc_aft'), axis=1)
metapkl = metapkl.astype({'dep': 'category', 'dep_bef': 'category', 'dep_aft': 'category'})                                           
print(metapkl['dep'].value_counts())
print(metapkl['dep_bef'].value_counts())
print(metapkl['dep_aft'].value_counts())
def f(row, col):
    if row[col] <= metapkl.quantile(0.15)['change']:
        return -1
    if row[col] <= metapkl.quantile(0.85)['change']:
        return 0
    else:
        return 1
    
metapkl['resp'] = metapkl.apply(lambda row: f(row, 'change'), axis=1)
metapkl = metapkl.astype({'resp': 'category'})                                           
print(metapkl['resp'].value_counts())

 0    198
 1     34
-1     34
Name: dep, dtype: int64
0    208
1     58
Name: dep_bef, dtype: int64
 0    188
-1     68
 1     10
Name: dep_aft, dtype: int64
 0    186
 1     40
-1     40
Name: resp, dtype: int64


In [53]:
def prepare_dfs(col='lyap', kind='processed'): 
    bands = {'delta', 'theta', 'alpha', 'beta', 'gamma'}
    band = None
    if col in bands:
        band = col
        col = 'ampl'
    df = pd.read_pickle(os.path.join(LABELED_ROOT, kind, col, f'training_{col}.pkl')) 
    df_bef = pd.read_pickle(os.path.join(LABELED_ROOT, kind, col, f'{col}_bef.pkl'))
    df_aft = pd.read_pickle(os.path.join(LABELED_ROOT, kind, col, f'{col}_aft.pkl'))
    if band is not None:
        df = df.loc[:, (slice(None), band)]
        df_bef = df_bef.loc[:, (slice(None), band)]
        df_aft = df_aft.loc[:, (slice(None), band)]
    return df, df_bef, df_aft
    
def prepare_resp_non(col='lyap'):
    df, df_bef, df_aft = prepare_dfs(col)
    df = df.drop(metapkl.columns, axis=1, errors='ignore')
    df.columns = df.columns.droplevel(1)
    df = df.join(metapkl)
    return df[df['dep'] == 1], df[df['dep'] == -1]

def prepare_dep_non(col='lyap'):
    df, df_bef, df_aft = prepare_dfs(col)
    df = df.drop(metapkl.columns, axis=1, errors='ignore')
    df.columns = df.columns.droplevel(1)
    df = df.join(metapkl)
    return df[df['dep'] == 1], df[df['dep'] == -1]

col = 'alpha'
df, df_bef, df_aft = prepare_dfs(col)
df_dep, df_nond =  prepare_dep_non(col)
df_resp, df_non = prepare_resp_non(col)
df

channel                FP1          FP2           F3           F4  \
measure              alpha        alpha        alpha        alpha   
patient trial                                                       
1       a       571.861251   662.103762   782.794500   640.377306   
        b       645.759505   691.611589   700.833887   828.837269   
3       a      5924.335478  5683.632607  5920.943765  5295.681431   
        b      4792.456295  4799.077882  4722.770438  4631.115054   
4       a      2707.834309  2832.053489  2159.352697  2524.658315   
        b      2718.251222  2728.426067  2220.125713  1973.311408   
5       a      3348.856191  3251.612691  3126.741666  2543.512794   
        b      2956.432791  2776.224844  2517.449472  1962.342137   
7       a      2177.943393  2277.595393  2058.149831  2314.584047   
        b      2057.212790  2088.860692  2166.001114  2163.199407   
9       a      1677.794568  1710.995638  1703.415693  1826.644709   
        b      2476.682130  2365.615433  2486.176012  2641.417264   
10      a       973.527418  1068.052581   716.871740   831.603673   
        b       462.245945   511.973033   423.009316   490.241836   
11      a      1740.950792  1977.666307  1611.417158  1855.754430   
        b      1615.438024  1776.033342  1492.323266  1804.972950   
12      a      1622.907280  1492.496320  1630.367410  1570.468392   
        b      1217.499891  1253.835500  1295.102552  1386.296203   
14      a      1349.271662  1430.836905  1296.157474  1352.964366   
        b       957.561480   992.231336   863.554930   923.230511   
15      a      1473.879916  1525.227506  1342.894371  1196.638710   
        b      2001.928417  2046.105525  1845.330591  1870.541243   
16      a      2827.314402  2875.940496  2792.970078  2814.608616   
        b      2188.516796  2236.296268  2201.648891  2140.110600   
17      a      1751.941222  1715.888291  1748.406623  1663.445397   
        b      1999.277487  1944.768174  1962.744312  1752.595513   
18      a      1466.737898  1489.261521  1173.070743  1052.770725   
        b      1497.465327  1678.351555  1382.055595  1292.131868   
19      a      2494.176983  2388.703781  2493.361958  2457.847584   
        b      3084.580684  2941.084658  3100.331657  3018.550894   
...                    ...          ...          ...          ...   
115     a      1005.230488  1116.365080   945.700348   967.860612   
        b      1930.329193  1924.464517  1624.777764  1692.149690   
116     a       953.017372   860.319391   922.008910   797.118437   
        b      1285.134238  1293.495191  1220.834294  1155.121453   
117     a      2305.577573  2244.884205  2356.703797  2214.277900   
        b      1953.837522  1945.487287  2149.861573  2034.142226   
119     a      1197.960824  1235.514296  1180.903277  1202.228992   
        b      1324.020503  1116.907322   839.981240   763.811428   
121     a      3037.010656  3004.543112  2844.162400  2919.545128   
        b      3654.274147  3712.103726  3236.216648  3656.013340   
122     a      3183.021574  3374.427522  3063.978658  3301.235301   
        b      3709.794398  3949.703932  3759.821881  3742.470676   
123     a      1514.690637  1434.846725  1226.608656  1054.629462   
        b      2124.387460  2127.028451  1704.727699  1574.100752   
124     a      2025.079532  2073.522077  2025.940198  2082.427386   
        b      1494.543711  1477.443634  1493.828511  1446.804950   
126     a       656.599528   822.896444   629.821520   816.084086   
        b       620.596455   668.877073   613.204790   615.609493   
127     a       953.843473  1008.451870  1051.779185  1078.566352   
        b       983.367023   987.319920  1062.573142   998.649542   
129     a       889.428402   960.735948   701.602547   764.651352   
        b      1497.642036  1497.759660  1412.319012  1344.699176   
130     a      1434.606140  1472.924747  1233.099126  1258.942505   
        b      1123.490536  1258.421067  1070.320025   976.819014  

In [43]:
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import (SelectFromModel, RFE, RFECV, SelectKBest, mutual_info_classif, chi2)
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm, grid_search, datasets
from genetic_selection import GeneticSelectionCV
from functools import wraps
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB

def print_params(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        print(f'{args} {kwargs}')
        res = f(*args, **kwargs)
        return res
    return wrapper

# @print_params
def predict(lab, ba, cols, estimator, evaluate_on_all=False, channels=CHANNEL_NAMES, selector=None, 
            print_incorrectly_predicted=False, show_selected=False):
    df, df_bef, df_aft = prepare_dfs('all')
    df = df.loc[(slice(None), slice(ba)), (channels, (cols))]
    X = df
    X.columns = df.columns.droplevel(1)
    X = X.drop(metapkl.columns, axis=1, errors='ignore')
    y = X.join(metapkl)[lab]
    X = X[y.isin([-1, 1])]
    y = y[y.isin([-1, 1])]
    
    if selector is not None:
        X = selector.fit_transform(X, y)
        if show_selected and hasattr(selector, 'support_'):
            print(df.columns.values[selector.support_])
    
    X_train, X_test, y_train, y_test = \
        train_test_split(
            X, y, test_size=0.3, random_state=213)
    
    unique, counts = np.unique(y_train, return_counts=True)
    print('Training distribution: ', dict(zip(unique, counts)))
    unique, counts = np.unique(y_test, return_counts=True)
    print('Testing distribution: ', dict(zip(unique, counts)))

    y_train = y_train.astype('int')

    estimator = estimator.fit(X_train, y_train)
    y_pred = estimator.predict(X_test)
    y_pred = y_pred.astype('int')
    y_test = y_test.astype('int')
    
    print("Accuracy score: %.2f" % metrics.accuracy_score(y_test, y_pred))
    print('Confusion matrix:\n', metrics.confusion_matrix(y_test, y_pred))
    print('Precision score: ', metrics.precision_score(y_test, y_pred, average='weighted'))
    print('Recall score: ', metrics.recall_score(y_test, y_pred, average='weighted'))
    print('f1 score: ', metrics.f1_score(y_test, y_pred, average='weighted'))
    print('ROC AUC score: ', metrics.roc_auc_score(y_test, y_pred, average='weighted'))
    # print('Coefficients: \n', np.array(X.stack().columns)[estimator.support_])
    
    if print_incorrectly_predicted:
        y_pred_s = pd.Series(y_pred, index=y_test.index)
        print('Incorrectly predicted:')
        print(pd.DataFrame(y_test[y_pred != y_test]).join(X))
    
    if evaluate_on_all:
        y_pred = estimator.predict(X)
        y_pred = y_pred.astype('int')

        print("Accuracy score: %.2f" % metrics.accuracy_score(y, y_pred))
        print('Confusion matrix:\n', metrics.confusion_matrix(y, y_pred))
        print('Precision score: ', metrics.precision_score(y, y_pred, average='weighted'))
        print('Recall score: ', metrics.recall_score(y, y_pred, average='weighted'))
        print('f1 score: ', metrics.f1_score(y, y_pred, average='weighted'))
        print('ROC AUC score: ', metrics.roc_auc_score(y, y_pred, average='weighted'))
        if print_incorrectly_predicted:
            y_pred_s = pd.Series(y_pred, index=y.index)
            print('Incorrectly predicted:')
            print(pd.DataFrame(y[y_pred != y]).join(X))
    return estimator


def scorer(estimator, X, y):
    y_pred = estimator.predict(X)
    # return metrics.accuracy_score(y, y_pred)
    # return (metrics.f1_score(y, y_pred, average='weighted', labels=np.unique(y_pred)))
            # + metrics.precision_score(y, y_pred, average='weighted') 
            # + metrics.recall_score(y, y_pred, average='weighted') 
            # + metrics.accuracy_score(y, y_pred))
    return metrics.roc_auc_score(y, y_pred, average='weighted')

In [ ]:
estimators = {
    svm.SVC(kernel='linear', class_weight='balanced'): {
        'C': [0.02, 0.5, 1.0, 1.5, 2, 5],
        'kernel': ('linear', 'poly', 'rbf', 'sigmoid'),
        'decision_function_shape' : ('ovo', 'ovr'),
    },
    LogisticRegression(class_weight='balanced'): {
        'C': [0.5, 1.0, 1.5, 2, 2.5, 3, 3.5],
        'penalty': ['l2', 'l1'],
    }
}

for estimator, params in estimators.items():
    # for cols in (('sampen',),):
    # for cols in (('dfa', 'higu', 'hurst'), ('dfa',), ('higu',), ('hurst'), ('dfa', 'hurst')):
    # for cols in (('dfa', 'higu', 'hurst', 'corr', 'lyap'), ('dfa',), ('higu',), ('hurst',), ('corr',), ('lyap',)):
    for cols in (('alpha',), ('beta',), ('gamma',), ('delta',), ('theta',),):
    # for cols in (('dfa',), ('dfa', 'lyap'), ('dfa', 'sampen'), ('dfa', 'corr')):
        for selector_name, selector in {
            'RFE': RFE(estimator), 
            'SelectFromModel': SelectFromModel(estimator), 
            'SelectKBest': SelectKBest(chi2, 5),
            'Genetic': GeneticSelectionCV(estimator,
                                      cv=3,
                                      verbose=0,
                                      scoring=scorer,
                                      n_population=50,
                                      crossover_proba=0.8,
                                      mutation_proba=0.2,
                                      n_generations=50,
                                      crossover_independent_proba=0.5,
                                      mutation_independent_proba=0.05,
                                      tournament_size=5,
                                      caching=True,
                                      n_jobs=-1),}.items():
            print(cols)
            print(selector_name)
            est = grid_search.GridSearchCV(estimator, params, iid=False, scoring=scorer)
            est = predict('resp', None, cols, est, show_selected=True, selector=selector)
            print(est.best_params_)
            print('\n\n')

('alpha',)
RFE


# RESULTS FOR FIRST AND LAST 15% QUANTILE OF CHANGE (30 / 30)

## Lyapunov exponent

In [47]:
estimator = LogisticRegression(C=3.5, penalty='l1', class_weight='balanced')
predict('resp', None, ('lyap',), estimator,
        channels=('FP2', 'F3', 'F4', 'C3', 'P3', 'P4', 'F7', 'F8', 'T6', 'Fz', 'Cz'))

Training distribution:  {-1: 24, 1: 22}
Testing distribution:  {-1: 10, 1: 10}
Accuracy score: 0.80
Confusion matrix:
 [[9 1]
 [3 7]]
Precision score:  0.8125
Recall score:  0.8
f1 score:  0.7979797979797979
ROC AUC score:  0.8


LogisticRegression(C=3.5, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l1', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

## DFA

In [49]:
estimator = LogisticRegression(C=2.5, penalty='l2', class_weight='balanced')
predict('resp', None, ('dfa',), estimator,
        channels=('FP1', 'FP2', 'F3', 'P4', 'O1', 'O2','T5', 'T6', 'Cz'))

Training distribution:  {-1: 24, 1: 22}
Testing distribution:  {-1: 10, 1: 10}
Accuracy score: 0.80
Confusion matrix:
 [[9 1]
 [3 7]]
Precision score:  0.8125
Recall score:  0.8
f1 score:  0.7979797979797979
ROC AUC score:  0.8


LogisticRegression(C=2.5, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

## Hurst exponent

In [48]:
estimator = LogisticRegression(C=3.5, penalty='l2', class_weight='balanced')
predict('resp', None, ('hurst',), estimator,
        channels=('FP1', 'FP2', 'F3', 'O1', 'F7', 'F8', 'T5', 'T6', 'Pz'))

Training distribution:  {-1: 24, 1: 22}
Testing distribution:  {-1: 10, 1: 10}
Accuracy score: 0.70
Confusion matrix:
 [[7 3]
 [3 7]]
Precision score:  0.7
Recall score:  0.7
f1 score:  0.7
ROC AUC score:  0.7


LogisticRegression(C=3.5, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

## Higuchi dimension
Results around 55%.

## Correlation dimension

In [44]:
estimator = svm.SVC(C=2, kernel='rbf', class_weight='balanced', decision_function_shape='ovo')
predict('resp', None, ('corr'), estimator, 
                   channels=('F3', 'F4', 'C4', 'O1', 'F7', 'F8', 'T5', 'T6', 'Cz'))

Training distribution:  {-1: 24, 1: 22}
Testing distribution:  {-1: 10, 1: 10}
Accuracy score: 0.90
Confusion matrix:
 [[9 1]
 [1 9]]
Precision score:  0.9
Recall score:  0.9
f1 score:  0.9
ROC AUC score:  0.9


SVC(C=2, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

# RESULTS FOR FIRST AND LAST TERCILE OF CHANGE (90 / 90)

## Lyapunov exponent

In [90]:
estimator = svm.SVC(C=1.5, kernel='rbf', class_weight='balanced', decision_function_shape='ovo')
predict('resp', None, ('lyap'), estimator, channels=('F3', 'F4', 'O1', 'O2', 'T6', 'Fz'))

Training distribution:  {-1: 51, 1: 47}
Testing distribution:  {-1: 23, 1: 19}
Accuracy score: 0.76
Confusion matrix:
 [[16  7]
 [ 3 16]]
Precision score:  0.7758526751661763
Recall score:  0.7619047619047619
f1 score:  0.7619047619047619
ROC AUC score:  0.7688787185354691


## DFA

In [15]:
# dfa_4_300_11.pkl
estimator = LogisticRegression(class_weight='balanced')
params = {'C': [0.5, 1.0, 1.5, 2, 2.5, 3, 3.5],
        'penalty': ['l2', 'l1'],}
estimator = grid_search.GridSearchCV(estimator, params, iid=False, scoring=scorer)
predict('resp', None, ('dfa',), estimator, channels=('C3', 'P4', 'F7', 'T6'))
estimator.best_params_

Training distribution:  {-1: 51, 1: 47}
Testing distribution:  {-1: 23, 1: 19}
Accuracy score: 0.71
Confusion matrix:
 [[16  7]
 [ 5 14]]
Precision score:  0.7188208616780045
Recall score:  0.7142857142857143
f1 score:  0.7149350649350649
ROC AUC score:  0.7162471395881007


{'C': 1.5, 'penalty': 'l2'}

### Alpha / Theta envelope
All estimators fail (50/50). Very similar values between groupds and small variance. There is still chance for depression score, however.

Same for sample entropy.

## Hurst exponent

In [97]:
estimator = LogisticRegression(C=3, penalty='l2', class_weight='balanced')
predict('resp', None, ('hurst',), estimator, channels=('P3', 'F7', 'T4', 'T6', 'Fz', 'Cz', 'Pz'))

Training distribution:  {-1: 51, 1: 47}
Testing distribution:  {-1: 23, 1: 19}
Accuracy score: 0.69
Confusion matrix:
 [[19  4]
 [ 9 10]]
Precision score:  0.6947278911564626
Recall score:  0.6904761904761905
f1 score:  0.6822001527883882
ROC AUC score:  0.6762013729977115


## Higuchi dimension

In [30]:
estimator = LogisticRegression(C=3, penalty='l1', class_weight='balanced')
selector = SelectKBest(chi2, 1)
estimator = predict('resp', None, ('higu',), estimator, selector=selector)
np.array(CHANNEL_NAMES)[selector.get_support()]

Training distribution:  {-1: 51, 1: 47}
Testing distribution:  {-1: 23, 1: 19}
Accuracy score: 0.69
Confusion matrix:
 [[13 10]
 [ 3 16]]
Precision score:  0.7233287545787546
Recall score:  0.6904761904761905
f1 score:  0.6867724867724869
ROC AUC score:  0.7036613272311213


array(['FP2'], dtype='<U3')

## Correlation dimension

In [34]:
estimator = LogisticRegression(C=3.5, penalty='l1', class_weight='balanced')
estimator = predict('resp', None, ('corr',), estimator, channels=('F4', 'C4', 'T5'))

Training distribution:  {-1: 51, 1: 47}
Testing distribution:  {-1: 23, 1: 19}
Accuracy score: 0.69
Confusion matrix:
 [[14  9]
 [ 4 15]]
Precision score:  0.7086640211640212
Recall score:  0.6904761904761905
f1 score:  0.6895983577775977
ROC AUC score:  0.6990846681922197
